import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';

import '../utils/nearby_demo_strings.dart';
import '../utils/cookie_constants.dart';
import '../services/web_cookies.dart';

/// 語言類型枚舉
enum LanguageType { zhTW, zhCN, en }

/// 多語言狀態管理
/// 支援繁體中文／簡體中文／英文切換。
///
/// 優先服務 **港、澳、臺、中** 等亞洲用戶；**英文**介面對應歐美等後續市場擴展。
/// 繁體以 `zh_HK` 區域格式為預設（港澳臺繁體用戶皆適用）。
class LanguageProvider with ChangeNotifier {
  // 當前語言（預設繁體中文）
  LanguageType _currentLang = LanguageType.zhTW;
  LanguageType get currentLang => _currentLang;

  /// 與 [LanguageType] 對應的 Flutter [Locale]，供 [MaterialApp.locale]、日期等系統元件使用。
  Locale get materialLocale {
    switch (_currentLang) {
      case LanguageType.zhTW:
        return const Locale('zh', 'HK');
      case LanguageType.zhCN:
        return const Locale('zh', 'CN');
      case LanguageType.en:
        return const Locale('en', 'US');
    }
  }

  /// Web：自 Cookie 還原介面語言（關閉分頁後仍保留）
  void hydrateLanguageFromCookie() {
    if (!kIsWeb) return;
    final code = WebCookies.read(CookieNames.lang);
    if (code == 'zh_CN') {
      _currentLang = LanguageType.zhCN;
    } else if (code == 'en') {
      _currentLang = LanguageType.en;
    } else if (code == 'zh_TW') {
      _currentLang = LanguageType.zhTW;
    }
    notifyListeners();
  }

  // 切換語言
  void setLanguage(LanguageType type) {
    _currentLang = type;
    if (kIsWeb) {
      final code = switch (type) {
        LanguageType.zhTW => 'zh_TW',
        LanguageType.zhCN => 'zh_CN',
        LanguageType.en => 'en',
      };
      WebCookies.write(
        CookieNames.lang,
        code,
        maxAgeSeconds: kPreferenceCookieMaxAgeDays * 24 * 60 * 60,
      );
    }
    notifyListeners(); // 通知UI刷新語言文字
  }

  // 根據key獲取對應語言的文字
  String getString(String key) {
    switch (_currentLang) {
      case LanguageType.zhTW:
        return _zhTW[key] ?? key; // 找不到就返回原key
      case LanguageType.zhCN:
        return _zhCN[key] ?? key;
      case LanguageType.en:
        return _en[key] ?? key;
    }
  }

  /// 字典無此 key 時使用備援字串，避免畫面顯示 raw key（例如熱重載未帶入新字典）。
  String getStringOr(
    String key, {
    required String zhTW,
    required String zhCN,
    required String en,
  }) {
    final v = getString(key);
    if (v != key) return v;
    switch (_currentLang) {
      case LanguageType.zhTW:
        return zhTW;
      case LanguageType.zhCN:
        return zhCN;
      case LanguageType.en:
        return en;
    }
  }

  /// 附近的人：示範／短 id 用戶邀聊提示（與 [NearbyDemoStrings] 一致，直接走此 getter 亦可）。
  String get nearbyDemoChatLine {
    switch (_currentLang) {
      case LanguageType.zhTW:
        return NearbyDemoStrings.zhTw;
      case LanguageType.zhCN:
        return NearbyDemoStrings.zhCn;
      case LanguageType.en:
        return NearbyDemoStrings.en;
    }
  }

  /// 活動／訂閱付款方式標籤。
  String paymentMethodLabelForActivity(String? code) {
    final c = code?.trim();
    if (c == null || c.isEmpty) return getString('payment_method_unknown');
    switch (c) {
      case 'stripe':
      case 'pending_stripe':
        return getString('payment_method_legacy_removed');
      case 'manual_fps_wechat_bank':
        return getString('pay_choice_manual');
      case 'iap_stores':
        return getString('pay_choice_iap');
      case 'iap_unavailable':
      case 'iap_unavailable_web':
        return getString('payment_method_iap_demo');
      default:
        return c;
    }
  }

  // 繁體中文字典
  final Map<String, String> _zhTW = {
    'app_name': 'Fast Dating',
    'login': '登入/註冊',
    'phone': '手機號',
    'password': '密碼',
    'send_code': '發送驗證碼',
    'signup_email_verification': '電郵驗證碼',
    'signup_email_code_hint': '6 位數驗證碼',
    'signup_get_code': '取得驗證碼',
    'signup_code_sent': '驗證碼已寄出，請查收郵件',
    'signup_verify': '驗證',
    'signup_email_verified': '✓ 電郵已驗證',
    'signup_need_verify': '請先驗證電郵',
    'signup_err_invalid_email': '請輸入正確的電子郵件',
    'signup_err_send_cooldown': '寄送過於頻繁，請稍候再試',
    'signup_err_email_send_failed': '無法寄出驗證信，請稍後再試',
    'signup_err_resend_unauthorized':
        'Resend API 金鑰無效或已撤銷，請在後台重設 RESEND_API_KEY 後再部署。',
    'signup_err_resend_domain':
        '寄件網域尚未在 Resend 驗證。請到 Resend 驗證你的網域，並在雲端設定 RESEND_FROM（顯示名 <noreply@你的網域>）。',
    'signup_err_resend_test_recipient':
        '目前為 Resend 測試模式：只會寄到你在 Resend 後台允許的收件人。請在 Resend 加入測試信箱，或改驗證正式網域與寄件人。',
    'signup_err_email_delivery_not_configured':
        '郵件寄送尚未設定完成，無法寄出驗證碼。請稍後再試或聯絡我們。',
    'signup_err_wrong_code': '驗證碼錯誤',
    'signup_err_otp_expired': '驗證碼已過期，請重新取得',
    'signup_err_no_otp_request': '請先按「取得驗證碼」',
    'signup_err_email_not_verified': '請先通過電郵驗證',
    'signup_err_gate_expired': '驗證已逾時，請重新取得驗證碼',
    'signup_err_email_in_use': '此電子郵件已被註冊',
    'signup_err_weak_password': '密碼需至少 6 個字元',
    'signup_err_name_too_short': '登入名稱至少 4 個字元',
    'signup_err_create_failed': '註冊失敗，請再試',
    'signup_err_no_firebase': '系統未連線，暫時無法註冊',
    'forgot_pwd': '忘記密碼',
    'register': '註冊',
    'home': '首頁',
    'message': '訊息',
    'message_list_guest_hint': '請先登入以查看訊息',
    'message_guest_dm_and_feed_hint':
        '登入後可查看與會員的私人訊息；以下仍顯示全站宣傳與活動資訊（與網頁版相同）。',
    'message_page_free_chat_quota_tip':
        '未訂閱會員：每人每日可與兩位（不同名）會員免費聊天。',
    'profile': '個人',
    'settings': '設定',
    'nearby': '附近的人',
    'menu': '選單',
    'file': '檔案',
    'publish': '邀聊通知',
    'publish_feed_empty_hint':
        '暫時沒有符合條件的貼文；若管理員已發佈全站宣傳，下拉此頁或按下方即可重新載入。',
    'publish_feed_retry': '重新載入貼文',
    'publish_invites_section_heading': '邀聊訊息',
    'publish_invites_section_intro':
        '不同會員經首頁發出邀請聊天通知時，邀請將顯示於此，你可選擇拒絕或接受。',
    'thinking_prompt': '你在想什麼？',
    'one_sentence': '一句話',
    'gift_shop': '禮品店',
    'chat': '聊天',
    'subscription_plan': '訂閱方案',
    'language': '語言',
    'font_size': '字體',
    'font_size_small': '細字體',
    'font_size_medium': '中字體',
    'font_size_large': '大字體',
    'font_size_small_short': '小',
    'font_size_large_short': '大',
    'notification': '提示',
    'notif_settings_title': '通知設定',
    'notif_section_background': '背景通知',
    'notif_heart_enabled': '按心通知',
    'notif_new_message_sound': '新訊息通知',
    'display': '顯示',
    'account': '帳戶',
    'about': '關於 Fast Dating',
    'terms': '條款及細則',
    'logout': '登出',
    'delete_account': '刪除帳戶',
    'region': '地區',
    'show_gender': '顯示我的性別',
    'show_on_platform': '將我顯示在 Fast Dating 上',
    'tags': '標籤',
    'filter': '篩選',
    'age_range': '年齡範圍',
    'show_other_gender': '顯示對方的性別',
    'male': '男性',
    'female': '女性',
    'interest': '興趣',
    'distance': '距離',
    'like': '喜歡',
    'pass': '略過',
    'match_success': '配對成功！',
    'chat_now': '立即聊天',
    'close': '關閉',
    'home_first_tip_body': '請按右下方想講～按鍵填好個人資料，按開始聊天。',
    'nearby_top_tip_body':
        '若之前在首頁無按想講～填資料，請現按右下角想講～填返，之後篩選條件進行聊天。',
    'nearby_demo_chat_hint': NearbyDemoStrings.zhTw,
    'cookie_banner_title': 'Cookie 與隱私',
    'cookie_banner_body':
        '我們使用必要 Cookie（含由伺服器設定的安全登入工作階段）以維持帳戶安全，並可儲存語言與顯示偏好。若你同意「分析」類別，我們會以匿名方式記錄頁面瀏覽摘要（不含聊天內容與密碼），以優化配對與服務。詳見設定內說明。',
    'cookie_accept_essential': '僅必要',
    'cookie_accept_all': '接受含分析',
    'cookie_rechoose': '重新選擇 Cookie 偏好',
    'lang_zh_tw': '繁體',
    'lang_zh_cn': '簡體',
    'lang_en': '英文',
    'notification_settings': '通知',
    'inappropriate_filter': '不當言詞過濾',
    'location_for_nearby': '位置顯示（附近配對）',
    'location_for_nearby_hint': '開啟後會使用 GPS，將座標傳給伺服器以取得真實附近用戶；關閉則不依定位載入。',
    'location_fetch_failed': '未取得定位，已改為不依 GPS 載入。',
    'location_nearby_reload_hint': '已儲存。請在「附近的人」按重新整理以套用。',
    'subscribed_plan': '訂閱的配對計劃',
    'current_account': '當前登入帳號',
    'activity_history': '參加活動記錄',
    'gender': '性別',
    'purchase_history': '購買記錄',
    'purchase_delete_activity_confirm': '確定刪除此活動報名紀錄？',
    'purchase_delete_unpaid_receipt_confirm': '確定刪除此筆未付款收據？',
    'purchase_activity_receipt_deleted': '已刪除此筆紀錄',
    'purchase_activity_receipt_delete_failed': '無法刪除，請稍後再試。',
    'follow_instagram': '追蹤 Instagram',
    'ad_coop': '廣告合作',
    'faq': '常見問題',
    'faq_video_body': '以下為常見問題相關說明影片，點擊下方即可於 YouTube 觀看。',
    'faq_open_youtube': '開啟 YouTube 影片',
    'contact_us': '聯絡我們',
    'contact_us_whatsapp_action': 'WhatsApp',
    'contact_us_email_label': '電郵',
    'user_terms': '使用者條款',
    'privacy_terms': '私隱條款',
    'privacy_policy_title': '私隱政策',
    'user_terms_title': '使用者條款',
    'user_terms_load_error': '無法載入使用者條款內容，請稍後再試。',
    'privacy_policy_load_error': '無法載入私隱政策內容，請稍後再試。',
    'privacy_settings': '私隱設定',
    'privacy_promo_section': '接收推廣及促銷',
    'privacy_direct_marketing': '同意直接促銷',
    'privacy_direct_marketing_footnote': '選擇了同意直接促銷即代表你同意我們使用你的個人資料聯絡向你進行促銷用途',
    'ad_post_requirement': '廣告合作刊登要求：30字內可加圖或link',
    'ad_fee_plan_title': '廣告刊登收費方案',
    'choose_subscription': '刊登廣告項目',
    'months': '個月',
    'subscription_terms':
        '定期扣款，可隨時取消，不設退款！透過 iTunes 帳戶，Apple Store 或 Google Play 等完成交易，訂閱生效後將於到期日 24 小時前以相同價錢自動續訂，直至取消。同意使用者條款及私隱條款。',
    'continue': '繼續',
    'ad_post': '廣告刊登內容',
    'ad_post_image': '圖',
    'ad_post_title': '標題',
    'ad_post_link': '可插入 link',
    'ad_post_content': '內容30字內',
    'ad_post_content_heading': '廣告刊登內容',
    'submit': '提交',
    'ad_post_record': '廣告刊登記錄',
    'ad_need_admin_approval': '廣告刊登內容發布後需經平台管理員審核通過才會發佈。',
    'ad_coop_firebase_not_ready': '無法同步：Firebase 尚未就緒，請稍後再試。',
    'ad_coop_login_required_sync': '請先登入會員帳戶後再提交，刊登內容才會同步至管理員審核。',
    'ad_coop_order_sync_failed': '無法寫入廣告訂單，已改以「僅貼文」同步；若持續失敗請聯絡客服。',
    'admin_ad_coop_submitted_at': '提交時間',
    'ad_post_submit_snackbar': '廣告內容已提交，待管理員審核～',
    'approved': '通過',
    'not_approved': '不通過',
    'pending_review': '待審核',
    'no_ad_posts': '暫無廣告刊登記錄',
    'ad_post_record_section_content': '刊登內容',
    'ad_post_record_section_orders': '訂單與付款',
    'ad_post_record_archived': '歷史版本',
    'ad_post_record_cloud': '已同步',
    'btn_edit': '修改',
    'ad_post_edit_title': '修改廣告刊登內容',
    'ad_post_delete_confirm': '確定刪除此貼文？此操作無法復原。',
    'ad_coop_history_deleted': '已刪除此筆已同步記錄。',
    'ad_post_remove_image': '移除圖片',
    'cancel': '取消',
    'subscribed_plan_content': '訂閱方案計劃內容',
    'subscribed_plan_tier_sync_hint': '此為帳戶訂閱層級同步顯示（尚無訂單文件時）；完成付款後會顯示訂單明細。',
    'upgrade_matching_action': '升級配對',
    'subscribed_plan_tier_badge': '層級',
    'subscribed_plan_upgrade_section_body':
        '與訂閱方案頁相同：開啟後可查看、修改每條問題與答案，儲存後與後台「升級配對資料庫」同步。',
    'subscription_fee': '費用',
    'subscription_date': '訂閱日期',
    'expiration_date': '失效日期',
    'auto_renewal': '自動續約',
    'enable_auto_renewal': '啟動自動續約',
    'no_subscription_records': '暫無已付費訂閱紀錄',
    'receipt_title': '收據',
    'payment_type_subscription': '訂閱方案',
    'payment_type_ad_coop': '廣告合作',
    'ad_coop_unpaid_order_delete_confirm': '確定刪除此筆未付款廣告合作訂單？',
    'ad_coop_unpaid_order_deleted': '已刪除訂單',
    'ad_coop_unpaid_order_delete_failed': '無法刪除，請稍後再試。',
    'payment_type_activity': '活動報名',
    'payment_item': '付款項目',
    'payment_receipt_content': '內容',
    'payment_amount': '金額',
    'payment_date': '日期時間',
    'payment_method': '付款方式',
    'no_purchase_records': '暫無購買記錄',
    'payment_method_unknown': '—',
    'payment_method_stripe': '已停用舊制網上付款',
    'payment_method_legacy_removed': '已停用舊制網上付款',
    'payment_method_manual_transfer': 'FPS／WeChat／銀行轉帳',
    'payment_method_iap_app_store': 'App Store 內購買',
    'payment_method_iap_google_play': 'Google Play 內購買',
    'payment_method_iap_other': '應用程式內購買',
    'payment_method_iap_demo': '請使用 iOS／Android App 完成應用程式內購買',
    'payment_success_check_receipt': '付款已成功，請去設定頁面查看收據。',
    'payment_status': '付款狀態',
    'payment_status_paid': '已付款',
    'payment_status_unpaid': '未付款',
    'payment_method_local_only': '本機紀錄',
    'activity_content': '活動內容',
    'no_activity_records': '暫無已付費活動記錄',
    'event_proposal': '提議活動方案',
    'login_banner': '品牌圖像',
    'login_banner_upload': '上傳品牌圖',
    'login_banner_upload_hint': '平台管理員可上傳圖片，會顯示於啟動頁、登入頁頂部，以及主分頁頂欄左側縮圖',
    'login_banner_intro': '平台管理員可分別上傳「啟動頁」與「登入頁」圖像。主分頁頂欄左側縮圖會使用登入頁圖像。',
    'splash_banner_title': '啟動頁圖像',
    'splash_banner_hint': '顯示於 App 啟動畫面中央',
    'splash_banner_upload': '上傳啟動頁圖像',
    'login_page_banner_title': '登入頁圖像',
    'login_page_banner_hint': '顯示於登入頁頂部；主分頁頂欄左側縮圖亦使用此圖',
    'login_page_banner_upload': '上傳登入頁圖像',
    'click_to_upload': '點擊上傳',
    'restore_default': '還原為預設',
    'banner_saved_splash': '已更新啟動頁圖像',
    'banner_saved_login': '已更新登入頁圖像',
    'banner_cleared_splash': '啟動頁已還原為預設圖形',
    'banner_cleared_login': '登入頁已還原為預設圖形',
    'banner_lock_switch': '鎖定圖像（鎖死後無法上傳、儲存或刪除）',
    'banner_locked_notice': '此圖像已鎖定，請先關閉鎖定後再變更',
    'admin_login_title': '管理員登入',
    'admin_account_label': '帳號',
    'admin_login_error': '帳號或密碼錯誤',
    'admin_login_roster_no_hash': '此帳號尚未設定名冊登入密碼，請由已登入管理員於列表「重置密碼」為您設定。',
    'admin_sign_in': '登入',
    'admin_remember_credentials': '記住帳號及密碼',
    'admin_forgot_password_link': '忘記密碼',
    'admin_forgot_password_body': '若忘記密碼，請聯絡系統管理員重設。應用程式內無法自行重設，請勿向他人洩露帳密。',
    'admin_settings_title': '管理員設定',
    'admin_settings_intro': '設定後台登入帳號與密碼。儲存後即刻生效，請妥善保管。',
    'admin_credentials_saved': '已儲存管理員帳密',
    'admin_credentials_empty': '請輸入帳號與密碼',
    'admin_restore_defaults': '還原預設帳密',
    'admin_restored_defaults': '已還原為預設帳密',
    'btn_save': '儲存',
    'btn_delete': '刪除',
    'admin_delete_order_confirm': '確定刪除此筆訂單？',
    'admin_logout': '登出',
    'admin_hub_title': '管理後台',
    'admin_pagination_prev': '上一頁',
    'admin_pagination_next': '下一頁',
    'admin_pagination_summary': '共 {count} 筆 · 第 {current} / {total} 頁',
    'admin_firebase_required':
        '無法讀寫後台資料：請確認 Firebase 已初始化，且管理員已以 Firebase Email／密碼建立連線。',
    'admin_firebase_retry': '重新連線',
    'admin_backend_firebase_not_ready':
        'Firebase 尚未初始化，後台無法連線資料庫。請重新整理頁面或檢查網路。',
    'admin_backend_auth_failed':
        '後台無法建立 Firebase 登入。請確認 Firebase 已啟用「Email／密碼」，並在 Authentication 建立與下方 Email 相同、密碼與管理員密碼相同的用戶。',
    'admin_backend_auth_admin_restricted':
        'Firebase 回傳「admin-restricted-operation」。請檢查：① Authentication → 設定 →「已授權網域」已加入此網站（如 fastdating1.com）。② 若啟用 App Check 強制驗證，請為 Web 設定或暫改監視模式。③ Users 已有與 App 設定相同的管理員 Email，且密碼與此處一致。',
    'admin_backend_auth_operation_not_allowed':
        'Firebase 未啟用 Email／密碼（operation-not-allowed）。請到 Firebase Console → Authentication → Sign-in method → 啟用「Email／密碼」。',
    'admin_backend_auth_dialog_title': '後台 Firebase 登入說明',
    'admin_backend_auth_user_not_found':
        'Firebase 尚未建立此 Email 帳號：{email}\n\n請到 Firebase Console → Authentication → Users →「新增使用者」，Email 請填上列完整字串，密碼須與管理員登入密碼相同；並在 Sign-in method 啟用「Email／密碼」。',
    'admin_backend_auth_wrong_password':
        'Firebase 密碼驗證失敗。請確認 Authentication → Users 內該 Email 的密碼與此處相同；或於 Console 重設密碼後再試。若 App 使用 ADMIN_FIREBASE_EMAIL 建置，請與該信箱一致。',
    'admin_backend_auth_invalid_email':
        'Firebase 不接受的 Email 格式。請檢查管理員帳號或聯絡開發者。',
    'admin_backend_auth_session_expired': '後台登入已過期，請重新登入管理員。',
    'profile_incomplete_title': '個人資料尚未填寫完整',
    'profile_incomplete_body':
        '配對需要公開「稱呼」、「職業」與「一句話」介紹（一句話不可為系統預設句）。請於「想講～」頁填好稱呼、職業與一句話後再使用。',
    'profile_incomplete_later': '稍後',
    'profile_incomplete_go_fill': '前往想講頁填寫',
    'admin_sec_a': '管理員帳戶（名冊）',
    'admin_sec_b': '會員登記資料',
    'admin_sec_c': '訂閱方案訂單',
    'admin_sec_d': '升級配對資料庫',
    'admin_sec_e': '活動訂單',
    'admin_sec_f': '活動',
    'admin_sec_f_editor': '活動編輯',
    'admin_sec_g': '提議活動方案審批',
    'admin_sec_h': '付款方式設定',
    'admin_sec_i': '廣告貼文訂單',
    'admin_sec_ad_approval_title': '廣告審批',
    'admin_sec_ad_promotion': '宣傳貼文',
    'admin_sec_ad_approval_intro': '以下與「廣告貼文訂單」相同資料來源，供專責審核會員提交之廣告貼文（文字／圖／連結）。',
    'admin_sec_i_approval_section': '廣告貼文審批',
    'admin_sec_i_months': '期數（月）',
    'admin_sec_i_amount': '金額（HKD）',
    'admin_sec_i_monthly_orders': '本月廣告訂單',
    'admin_sec_i_monthly_paid_total': '本月已付款合計',
    'admin_ad_coop_pass': '通過',
    'admin_ad_coop_issue': '有問題',
    'admin_ad_coop_delete_submission_confirm':
        '確定刪除此筆提交之廣告貼文內容？若有廣告合作訂單，訂單紀錄仍保留；會員可重新提交貼文。',
    'admin_ad_coop_issue_title': '請填寫需修改原因',
    'admin_ad_coop_issue_reason': '原因',
    'admin_ad_coop_issue_required': '請輸入原因',
    'admin_ad_coop_review_none': '審核：未標示',
    'admin_ad_coop_review_passed': '審核：已通過',
    'admin_ad_coop_review_pending': '審核：待審／待重審',
    'admin_ad_coop_review_revision': '審核：請修改',
    'admin_ad_coop_image_only_hint': '（僅圖片，無文字）',
    'admin_ad_coop_view_content_btn': '查看廣告貼文內容',
    'admin_ad_coop_content_dialog_title': '會員提交的廣告貼文',
    'admin_ad_coop_content_empty': '尚無文字、圖片或連結（請確認會員已於廣告合作頁提交並同步至訂單）。',
    'admin_sec_i_standalone_section': '僅廣告貼文（無訂單）',
    'admin_sec_ad_approval_records_section': '待審核貼文（會員廣告貼文記錄）',
    'admin_sec_ad_approval_linked_note':
        '此貼文已同步至會員之廣告訂單；審核結果會寫入訂單與通知（本頁不顯示付款資料）。',
    'admin_ad_approval_publication_heading': '廣告刊登內容',
    'admin_sec_i_standalone_note': '此會員尚未建立廣告合作訂單；可審核貼文內容並通知對方。',
    'admin_ad_promotion_title': '標題',
    'admin_ad_promotion_link': '連結',
    'admin_ad_promotion_content': '內容',
    'admin_ad_promotion_upload': '上載圖片',
    'admin_ad_promotion_duration': '發佈期限',
    'admin_ad_promotion_publish': '發佈',
    'admin_ad_promotion_published': '宣傳貼文記錄',
    'admin_ad_promotion_empty': '尚未有宣傳貼文記錄。',
    'admin_ad_promotion_pause': '暫停',
    'admin_ad_promotion_edit': '編輯',
    'admin_ad_promotion_cancel_edit': '取消編輯',
    'admin_ad_promotion_editing_banner': '正在編輯一則貼文；修改後按下方按鈕即可更新並重新發佈。',
    'admin_ad_promotion_save_publish': '儲存並發佈',
    'admin_ad_promotion_updated_ok': '已更新並發佈宣傳貼文。',
    'admin_ad_promotion_republish': '重新發佈',
    'admin_ad_promotion_publish_ok': '已發佈宣傳貼文。',
    'admin_ad_promotion_publish_failed': '發佈失敗，請稍後再試。',
    'admin_ad_promotion_paused_ok': '已暫停宣傳貼文。',
    'admin_ad_promotion_republish_ok': '已重新發佈宣傳貼文。',
    'admin_ad_promotion_title_required': '請先填寫標題。',
    'admin_ad_promotion_content_required': '請至少填寫內容、連結或圖片。',
    'admin_ad_promotion_invalid_image': '圖片格式不支援或處理失敗，請改用 JPG / PNG。',
    'ad_coop_notify_approved': '您的廣告貼文內容已通過審核。',
    'ad_coop_notify_revision': '管理員請您修改廣告貼文：',
    'ad_coop_notify_dismiss': '關閉',
    'ad_coop_billing_notify_title': '廣告刊登通知',
    'admin_sec_j': '廣告到期提示',
    'admin_sec_k': '懷疑違規內容',
    'admin_sec_k_empty': '目前沒有待審貼文',
    'admin_sec_k_approved': '已批准並發佈至邀聊通知',
    'admin_sec_k_rejected': '已拒絕並刪除此則待審貼文',
    'admin_sec_k_tab_pending': '待審貼文',
    'admin_sec_k_tab_reports': '會員舉報',
    'admin_sec_k_reports_empty': '目前沒有待處理舉報',
    'admin_report_post_label': '貼文 ID',
    'admin_report_author_label': '作者',
    'admin_report_reason_label': '舉報說明',
    'admin_report_ignore': '不理',
    'admin_report_delete_post': '刪除貼文',
    'admin_report_warn': '警告',
    'admin_report_blacklist': '加入黑名單',
    'admin_report_ignored': '已標記為不理',
    'admin_report_deleted': '已刪除公開貼文',
    'admin_report_warned': '已向會員發出警告（請修改貼文）',
    'admin_report_blacklisted': '已加入黑名單並同步會員帳戶',
    'moderation_contact_blocked': '內容不得包含電話、電郵、網址或社群聯絡方式，請修改後再發佈。',
    'feed_report_button': '舉報',
    'feed_report_title': '舉報違規內容',
    'feed_report_hint': '請簡述違規情況（例如：騷擾、不當圖片、聯絡方式外洩等）。',
    'feed_report_field_hint': '輸入舉報內容…',
    'feed_report_submit': '提交',
    'feed_report_cancel': '取消',
    'feed_report_ok': '已提交舉報，管理員會跟進。',
    'feed_report_need_login': '請先登入後再舉報。',
    'feed_report_empty': '請填寫舉報說明。',
    'feed_report_fail': '提交失敗',
    'moderation_blocked': '內容含有不當用語，無法發佈。',
    'moderation_queued': '內容已送交管理員審核，通過後會顯示於「邀聊通知」。',
    'moderation_need_login_review': '請先登入會員帳戶，以便將內容送交管理員審核。',
    'duplicate_same_day': '24 小時內已發佈過相同內容，請稍後或修改後再發佈。',
    'my_posts_header': '已發佈的貼文（請避免 24 小時內重複相同內容）：',
    'my_posts_empty': '尚無已發佈貼文',
    'post_edit': '修改',
    'post_delete': '刪除',
    'post_edit_hint': '輸入貼文內容',
    'confirm_delete_post_title': '確定刪除此則貼文？',
    'post_deleted': '已刪除貼文',
    'post_delete_failed': '刪除失敗，請稍後再試',
    'post_updated': '已更新貼文',
    'moderation_suspected_edit': '內容需管理員審核後才會更新顯示。',
    'load_more_feed': '載入更多',
    'feed_post_image_title': '發布貼文圖片',
    'feed_post_image_hint': '與上方訊息大頭照分開；此圖會顯示於「邀聊通知」貼文（可選）。',
    'feed_post_image_tap': '點擊上載',
    'image_moderation_blocked': '圖片未通過安全檢測（可能為不雅、色情或檔案損壞），無法與貼文一併發佈。',
    'admin_sec_a_add': '新增名冊項目',
    'admin_sec_a_new_expand': '新增管理員帳戶',
    'admin_sec_a_account_name': '管理員帳戶名稱',
    'admin_sec_a_recovery_email': '後備電郵（重設密碼用）',
    'admin_sec_a_password_hint':
        '若填寫密碼，將以「後備電郵」在 Firebase 建立帳號（須與 Authentication 不重複）。留空則僅寫入名冊，請稍後於 Console 手動建立使用者。',
    'admin_sec_a_set_password': '設置密碼（選填）',
    'admin_sec_a_submit': '提交',
    'admin_sec_a_list_title': '現有管理員帳戶列表',
    'admin_sec_a_col_name': '帳戶名稱',
    'admin_sec_a_col_reset': '更改密碼',
    'admin_sec_a_col_recovery': '後備電郵',
    'admin_sec_a_col_delete': '刪除帳戶',
    'admin_sec_a_col_manual_reset': '重置密碼',
    'admin_sec_a_manual_reset_title': '重置名冊登入密碼',
    'admin_sec_a_manual_reset_hint': '新密碼將與管理員登入頁的「帳號」「密碼」一致（帳號為左列帳戶名稱）。',
    'admin_sec_a_new_password': '新密碼',
    'admin_sec_a_confirm_password': '確認密碼',
    'admin_sec_a_password_mismatch': '兩次密碼不一致',
    'admin_sec_a_manual_reset_submit': '確定',
    'admin_sec_a_manual_reset_ok': '已更新；請用新密碼登入後台。',
    'admin_sec_a_change_password': '寄送重設信',
    'admin_sec_a_reset_sent': '已寄出密碼重設郵件',
    'admin_sec_a_reset_fail': '寄送失敗',
    'admin_sec_a_recovery_required': '請先填寫後備電郵',
    'admin_sec_a_required_fields': '請填寫帳戶名稱與後備電郵',
    'admin_sec_a_added': '已新增名冊',
    'admin_sec_a_added_no_password': '已加入名冊；尚未設定登入密碼，請填寫「密碼」重新提交或由其他管理員「重置密碼」。',
    'admin_sec_a_added_shared_email':
        '此後備電郵已為會員或既有帳號，已加入管理員名冊（可同時為會員與管理員）。未另建 Firebase 使用者；重設密碼將寄至該電郵之既有帳號。',
    'admin_sec_a_add_fail': '新增失敗',
    'admin_sec_a_edit_recovery': '編輯後備電郵',
    'admin_forgot_enter_account': '請輸入帳號',
    'admin_forgot_enter_email': '請輸入後備電郵',
    'admin_forgot_submit': '更改密碼（寄送重設信）',
    'admin_forgot_mismatch': '帳號與後備電郵與名冊不符',
    'admin_forgot_sent': '若資料正確，已寄出重設密碼郵件，請查收信箱。',
    'admin_forgot_firebase': 'Firebase 未就緒，無法驗證名冊或寄信。',
    'admin_forgot_roster_body':
        '管理員後台登入密碼儲存在「管理員帳戶」名冊。若忘記，請聯絡其他已能登入的管理員，在名冊列表為您按「重置密碼」設定新密碼後即可登入。',
    'admin_forgot_fail': '處理失敗',
    'admin_sec_display_name': '顯示名稱',
    'admin_sec_note': '備註',
    'admin_sec_empty': '尚無資料',
    'admin_sec_deleted': '已刪除',
    'admin_sec_b_tab_members': '會員與統計',
    'admin_sec_b_tab_blacklist': '黑名單',
    'admin_sec_b_total': '註冊會員總數',
    'admin_sec_b2_add': '加入黑名單',
    'admin_sec_c_add_order': '新增訂單',
    'admin_sec_c_monthly': '本月訂單數',
    'admin_sec_c_monthly_paid_line': '本月已付款：{amount}',
    'admin_sec_c_renewal_total': '續訂總數：{n}',
    'admin_sec_c_expiry_hint': '未來 30 日內到期',
    'admin_sec_c_expires': '到期日',
    'admin_sec_c_plan': '方案代碼',
    'admin_sec_c_member': '會員資料',
    'admin_sec_c_order_status': '訂單狀態',
    'admin_sec_c_deal_done': '成交',
    'admin_sec_c_deal_pending': '未成交',
    'admin_pay_other': '其他',
    'admin_sec_c_receipt_missing': '尚未上傳收據',
    'admin_sec_c_mark_paid_needs_receipt': '此付款方式須先有收據圖片，方可標記為已付款。',
    'admin_sec_c_pay_state': '付款狀態',
    'admin_sec_c_paid': '已付款',
    'admin_sec_c_unpaid': '未付款',
    'admin_sec_c_btn_mark_paid': '已付款',
    'admin_sec_c_receipt': '收據',
    'admin_sec_c_pay_method': '付款方式',
    'admin_sec_c_order_time': '訂單時間',
    'admin_pay_manual_fps_wechat_bank': '其他（FPS／WeChat Pay／銀行轉帳）',
    'admin_pay_other_demo_web': '其他（示範／Web 無法使用商店）',
    'admin_pay_other_demo': '其他（示範）',
    'admin_pay_stripe': '已停用舊制付款',
    'admin_pay_iap_ios': 'App Store（IAP）',
    'admin_pay_iap_android': 'Google Play（IAP）',
    'admin_sec_d_add': '加入配對庫',
    'admin_sec_e_criteria': '配對條件（依要求配對）',
    'admin_sec_e_push': '活動推送通知（寫入通知佇列）',
    'admin_sec_e_push_btn': '排程推送',
    'admin_sec_e_push_queued': '已寫入通知佇列',
    'admin_sec_e_activity_orders': '活動訂單數目',
    'admin_sec_e_monthly_count': '本月訂單：{n} 筆',
    'admin_sec_e_monthly_paid_label': '已付款',
    'admin_sec_e_monthly_paid_total': '本月合計：{amount}',
    'admin_sec_e_activity_empty': '尚無活動報名訂單（會員於前台活動頁完成報名後會顯示）。',
    'admin_sec_e_purged_unpaid': '已自動刪除 {n} 筆逾一個月未付款的活動訂單。',
    'admin_purge_unpaid_orders_snackbar': '已自動刪除 {n} 筆逾一個月未付款的訂單（訂閱／廣告／活動）。',
    'admin_manual_sweep_title': '手動月繳即時檢查',
    'admin_manual_sweep_body':
        '按一下即可立即執行手動月繳 sweep，不用等每日排程。系統會即時補發提醒、停權逾期未付款會員，並更新相關訂單與會員狀態。',
    'admin_manual_sweep_btn': '立即執行 sweep',
    'admin_manual_sweep_running': '執行中…',
    'admin_manual_sweep_done': '已即時執行手動月繳檢查，更新 {n} 筆紀錄。',
    'admin_ad_coop_sweep_done': '已即時執行廣告刊登月繳檢查，更新 {n} 筆紀錄。',
    'admin_activity_summary': '活動內容摘要',
    'admin_sec_f_add': '新增活動',
    'admin_sec_f_upload_image': '上載圖片',
    'admin_sec_f_images': '圖片網址（逗號分隔）',
    'admin_sec_f_payment': '付款說明',
    'admin_sec_f_gmail': 'Gmail 通知（標記，實際寄信需 Cloud Functions）',
    'admin_sec_f_price': '價錢',
    'admin_sec_f_activity_detail': '活動詳情（報名頁）',
    'admin_sec_f_event_poster_upload': '上載活動海報（報名頁「了解詳情」右上角）',
    'admin_sec_f_view_activity_detail': '顯示活動詳情',
    'admin_sec_f_remove_event_poster': '移除海報',
    'admin_sec_f_tap_area_to_upload': '點擊框內上載圖片',
    'admin_sec_f_poster_rules': '僅支援 JPG、PNG；單檔 5MB 內，超過將自動壓縮。',
    'admin_sec_f_poster_invalid_format': '請選擇 JPG 或 PNG 圖片。',
    'admin_sec_f_list_poster_placeholder': '圖片',
    'admin_sec_f_activity_detail_hint': '顯示於活動標題下方，例如流程、地點、注意事項',
    'admin_sec_f_body_hint': '列表與同步用內文；若未填「價錢」，第一行可作價錢顯示（舊版相容）。',
    'admin_sec_f_activity_dates_title': '活動日期',
    'admin_sec_f_activity_dates_hint':
        '可新增多個不同日期；會員於報名頁可橫向滑動選擇。若留白則不顯示日期選擇。',
    'admin_sec_f_activity_dates_add': '新增日期欄',
    'admin_sec_f_activity_date_placeholder': '例：2025年6月14日（六）',
    'admin_sec_f_registration_cap': '報名人數（參加者單次可選 1～10 人；不設活動總報名上限）',
    'pay_choice_iap': 'App Store／Google Play',
    'pay_choice_stripe': '已停用舊制網上付款',
    'pay_choice_manual': 'FPS／WeChat／銀行戶口',
    'payment_manual_orange_hint_above': '按下面橙鍵付款',
    'subscription_iap_subtitle': '依裝置使用 App Store 或 Google Play 付款',
    'subscription_stripe_subtitle': '此付款方式已停用',
    'subscription_manual_subtitle': '按上面橙鍵進行付款',
    'activity_details_label': '活動詳情',
    'activity_reg_event_date': '活動日期',
    'activity_reg_pick_event_date': '選擇活動日期',
    'activity_reg_swipe_right_select_gt': '向右滑動選擇》',
    'activity_reg_swipe_right_select': '向右滑動選擇',
    'activity_tap_image_enlarge': '按圖放大',
    'activity_scroll_pay_banner': '向下滑動付款完成報名',
    'activity_scroll_down_hint': '向下滑動',
    'activity_reg_headcount': '報名人數',
    'activity_choose_payment': '付款方式',
    'activity_payment_tap_hint': '按上面橙鍵進行付款',
    'activity_login_required': '請先登入一般會員帳戶（勿使用訪客）以報名及付款。',
    'activity_order_failed': '無法建立訂單，請確認已登入或網路正常。',
    'activity_stripe_url_missing': '此舊制網上付款方式已停用。',
    'activity_order_manual_snackbar': '已提交活動報名訂單，請於 WhatsApp 傳送收據。',
    'activity_whatsapp_prefill': '我想報名活動：',
    'activity_whatsapp_prefill_tail': ' 位，總額 ',
    'activity_iap_demo_snackbar': '（示範）已記錄活動報名。',
    'activity_iap_use_app': '應用程式內購買請使用 iOS／Android App 完成。',
    'admin_sec_f_saving': '儲存中…',
    'admin_sec_f_sync_failed': '活動已寫入後台，但同步至前台活動列表失敗：{error}。請檢查網路或重新整理活動頁。',
    'admin_sec_f_empty_hint':
        '點右下角「新增活動」；填寫名稱、活動詳情（報名頁）、報名人數、價錢與付款方式後按「儲存」會同步至前台活動頁。',
    'admin_sec_f_title_required': '請輸入活動名稱',
    'admin_sec_f_delete_confirm': '確定刪除此活動？此操作無法復原。',
    'admin_sec_g_emails': '報告收件人 Email（逗號分隔）',
    'admin_sec_g_cadence': '報告頻率',
    'admin_sec_g_monthly': '每月',
    'admin_sec_g_weekly': '每週',
    'admin_sec_h_new': '新增測試申請',
    'admin_sec_company': '公司／名稱',
    'admin_sec_contact': '聯絡方式',
    'admin_sec_approve': '通過',
    'admin_sec_reject': '拒絕',
    'admin_sec_reject_reason': '拒絕原因（必填）',
    'admin_sec_h_approved': '已通過',
    'admin_sec_j_empty': '14 日內無即將到期之已核准廣告',
    'admin_sec_j_expires': '到期日',
    'admin_field_uid': '會員 UID',
    'admin_field_reason': '原因',
    'admin_sec_saved': '已儲存',
    'admin_save_failed': '儲存失敗',
    'admin_src_a':
        'Firestore「admin_accounts」：後台管理員名冊（與 App 內本機管理員帳密分開）。欄位：displayName、note、active、createdAt。',
    'admin_src_b':
        '「users」：註冊/登入與個人檔同步（memberNo、email、displayName、phone、gender、age、subscriptionActive、tags、sentence、avatar、updatedAt）。「user_blacklist」：以 UID 阻擋。',
    'admin_src_c':
        '「subscription_orders」：後台補登訂單；「payments」「subscriptions」：App／IAP 與歷史付款資料之紀錄（與 PaymentBackendService 設計一致）。',
    'admin_src_d':
        '「upgrade_matching_pool」：升級配對候選；可從 users.subscriptionActive＝true 同步。另見「matches」互配、「users」探索。',
    'admin_src_e':
        '「match_admin_settings」：配對條件；「notifications」type=admin_event：推送佇列（FCM 需 Cloud Functions）。',
    'admin_src_f':
        '「event_cms」：後台活動文案；App 活動列表為「activities」（ActivityFirestoreService）。',
    'admin_src_g': '「event_proposals」：會員提議之活動方案；管理員可標示通過或落選（status）。',
    'admin_src_h':
        '「ad_partner_requests」status=pending：審批中（拒絕須填 rejectReason）。',
    'admin_src_i': '同集合 status=approved：審批通過案例。',
    'admin_src_j':
        '同集合 approved 且 expiresAt 將屆：到期提示（排程寄信需 Scheduler／Functions）。',
    'admin_sec_c_app_records': 'App 付款／訂閱集合（只讀預覽）',
    'admin_sec_d_sync': '同步訂閱中會員至配對庫',
    'admin_sec_d_sync_ok': '已同步',
    'admin_sec_member_no': '會員編號',
    'admin_sec_b_reg_date': '登記日期',
    'admin_sec_b_add_blacklist': '加入黑名單',
    'admin_sec_b2_checkbox_reason': '後台名單勾選',
    'admin_sec_subscribed': '已訂閱',
    'admin_sec_b_cleanup_scan': '掃描並刪除資料不齊占位',
    'admin_sec_b_cleanup_title': '刪除占位配對資料',
    'admin_sec_b_cleanup_body':
        '將刪除「users」中：職業為「未填寫」且個人句仍為系統預設句的帳號（首頁自動補齊之占位）。已自訂簡介者不會刪除。單次最多掃描 500 筆 job=未填寫。會排除您目前 Firebase 登入的 UID。',
    'admin_sec_b_cleanup_found': '符合條件',
    'admin_sec_b_cleanup_confirm': '確認刪除',
    'admin_sec_b_cleanup_done': '已刪除',
    'admin_sec_b_cleanup_none': '沒有符合條件的占位會員',
    'admin_sec_b_cleanup_unit': '筆',
    'event_proposal_record': '提議活動方案記錄',
    'event_name': '活動名稱',
    'event_promo_image': '活動宣傳圖片',
    'event_promo_upload_whatsapp_hint': '上傳活動宣傳圖片，請按左邊WhatsApp上傳～',
    'event_content': '活動內容',
    'event_venue': '舉行的地方',
    'event_date': '日期',
    'event_time': '時間',
    'event_cost': '活動成本價',
    'event_proposal_note': '閣下提議活動方案一經被採納，可免費參加其活動一次',
    'event_content_placeholder': '地方、日期、時間',
    'adopted': '採納',
    'not_adopted': '不採納',
    'event_proposal_status_passed': '通過',
    'event_proposal_status_rejected': '落選',
    'event_proposal_edit_mode': '修改提議',
    'event_proposal_delete_confirm': '確定刪除此提議紀錄？此操作無法復原。',
    'event_proposal_duplicate': '提議內容與既有紀錄重複，請修改後再提交。',
    'event_proposal_submit_failed': '無法提交：請確認已登入且網路正常，稍後再試。',
    'event_proposal_login_required':
        '無法提交：請檢查網路；若仍失敗，請在 Firebase 主控台啟用「匿名」登入方式。',
    'event_proposal_timeout': '提交逾時（常見於圖片過大或網路慢）。請改選較小圖片或稍後再試。',
    'event_proposal_record_modify': '修改',
    'event_proposal_image_failed': '圖片上傳失敗（常見原因：儲存權限未開放）。請重試或聯絡管理員。',
    'storage_upload_anonymous_no_image':
        '匿名登入無法上傳圖片至雲端儲存。請改用 Email／Google／Apple 登入後再試。',
    'no_event_proposals': '暫無提議活動方案記錄',
    'chat_quota_free_hint':
        '未訂閱會員：每個曆日在訊息功能內，最多與 2 位「不同會員」聊天（依帳號辨識，新舊會員或暱稱不影響）；與同一人同日不另計名額。管理員確認已收款後，訂閱生效可無限聊。',
    'chat_quota_paywall':
        '每日免費只可與兩位會員聊天，請成功訂閱方案後，不限次數與其他會員進行聊天。',
    'chat_quota_dialog_title': '免費聊天名額已滿',
    'chat_quota_go_subscribe': '請訂閱方案',
    'messaging_requires_invite_accept': '請先邀請對方，待對方於「邀聊通知」接受後才可進入訊息聊天。',
    'heart_counter_invite_followup': '已記錄互相關注。請發起邀聊，對方接受後即可進入訊息頁面聊天。',
    'match_mutual_invite_body': '你和對方互相喜歡！請發出邀聊，對方接受後即可進入訊息頁面聊天。',
    'send_chat_invitation': '發出邀聊',
    'chat_invite_interest_body': '有人對你的資料有興趣，想與對方聊天嗎？',
    'chat_invite_btn_want': '接受',
    'chat_invite_btn_decline': '拒絕',
    'chat_invite_popup_title': '邀聊通知',
    'chat_invite_popup_agree': '同意',
    'chat_invite_popup_reject': '拒絕',
    'chat_invite_accept_failed_missing':
        '找不到此邀請，可能尚未同步或被撤回，請下拉重新整理。',
    'chat_invite_accept_failed_already':
        '此邀請已被處理（可能已在其他裝置接受），請下拉重新整理。',
    'chat_invite_accept_failed_unknown': '暫無法接受邀請，請稍後再試。',
  };

  // 簡體中文字典
  final Map<String, String> _zhCN = {
    'app_name': 'Fast Dating',
    'login': '登录/注册',
    'phone': '手机号',
    'password': '密码',
    'send_code': '发送验证码',
    'signup_email_verification': '电邮验证码',
    'signup_email_code_hint': '6 位数字验证码',
    'signup_get_code': '取得验证码',
    'signup_verify': '验证',
    'signup_email_verified': '✓ 电邮已验证',
    'signup_need_verify': '请先验证电邮',
    'signup_err_invalid_email': '请输入正确的电邮',
    'signup_err_send_cooldown': '发送过于频繁，请稍候再试',
    'signup_err_email_send_failed': '无法寄出验证邮件，请稍后再试',
    'signup_err_email_delivery_not_configured':
        '邮件寄送尚未配置完成，无法寄出验证码。请稍后再试或联系我们。',
    'signup_err_wrong_code': '验证码错误',
    'signup_err_otp_expired': '验证码已过期，请重新取得',
    'signup_err_no_otp_request': '请先按「取得验证码」',
    'signup_err_email_not_verified': '请先通过电邮验证',
    'signup_err_gate_expired': '验证已逾时，请重新取得验证码',
    'signup_err_email_in_use': '此电邮已被注册',
    'signup_err_weak_password': '密码需至少 6 个字符',
    'signup_err_name_too_short': '登入名称至少 4 个字符',
    'signup_err_create_failed': '注册失败，请重试',
    'signup_err_no_firebase': '系统未连接，暂无法注册',
    'forgot_pwd': '忘记密码',
    'register': '注册',
    'home': '首页',
    'message': '消息',
    'message_list_guest_hint': '请先登录以查看消息',
    'message_guest_dm_and_feed_hint':
        '登录后可查看与会员的私人消息；以下仍显示全站宣传与活动信息（与网页版相同）。',
    'message_page_free_chat_quota_tip':
        '未订阅会员：每人每日可与两位（不同名）会员免费聊天。',
    'profile': '个人',
    'settings': '设置',
    'nearby': '附近的人',
    'menu': '菜单',
    'file': '档案',
    'publish': '邀聊通知',
    'publish_feed_empty_hint':
        '暂时没有符合条件的帖子；若管理员已发布全站宣传，下拉此页或点击下方即可重新载入。',
    'publish_feed_retry': '重新载入帖子',
    'publish_invites_section_heading': '邀聊讯息',
    'publish_invites_section_intro':
        '不同会员经首页发出邀请聊天通知时，邀请将显示于此，你可选择拒绝或接受。',
    'thinking_prompt': '你在想什么？',
    'one_sentence': '一句话',
    'gift_shop': '礼品店',
    'chat': '聊天',
    'subscription_plan': '订阅方案',
    'language': '语言',
    'font_size': '字体',
    'font_size_small': '细字体',
    'font_size_medium': '中字体',
    'font_size_large': '大字体',
    'font_size_small_short': '小',
    'font_size_large_short': '大',
    'notification': '提示',
    'notif_settings_title': '通知设定',
    'notif_section_background': '背景通知',
    'notif_heart_enabled': '按心通知',
    'notif_new_message_sound': '新消息通知',
    'display': '显示',
    'account': '账户',
    'about': '关于 Fast Dating',
    'terms': '条款及细则',
    'logout': '登出',
    'delete_account': '删除账户',
    'region': '地区',
    'show_gender': '显示我的性别',
    'show_on_platform': '将我显示在 Fast Dating 上',
    'tags': '标签',
    'filter': '筛选',
    'age_range': '年龄范围',
    'show_other_gender': '显示对方的性别',
    'male': '男性',
    'female': '女性',
    'interest': '兴趣',
    'distance': '距离',
    'like': '喜欢',
    'pass': '略过',
    'match_success': '配对成功！',
    'chat_now': '立即聊天',
    'close': '关闭',
    'home_first_tip_body': '请按右下方想讲～按键填好个人资料，按开始聊天。',
    'nearby_top_tip_body':
        '若之前在首页无按想讲～填资料，请现按右下角想讲～补填，之后筛选条件进行聊天。',
    'nearby_demo_chat_hint': NearbyDemoStrings.zhCn,
    'cookie_banner_title': 'Cookie 与隐私',
    'cookie_banner_body':
        '我们使用必要 Cookie（含由服务器设置的安全登录会话）以维持账户安全，并可保存语言与显示偏好。若你同意「分析」类别，我们会以匿名方式记录页面浏览摘要（不含聊天内容与密码），以优化配对与服务。',
    'cookie_accept_essential': '仅必要',
    'cookie_accept_all': '接受含分析',
    'cookie_rechoose': '重新选择 Cookie 偏好',
    'lang_zh_tw': '繁体',
    'lang_zh_cn': '简体',
    'lang_en': '英文',
    'notification_settings': '通知',
    'inappropriate_filter': '不当言词过滤',
    'location_for_nearby': '位置显示（附近配对）',
    'location_for_nearby_hint': '开启后会使用 GPS，将坐标传给服务器以获取真实附近用户；关闭则不依定位载入。',
    'location_fetch_failed': '未取得定位，已改为不依 GPS 载入。',
    'location_nearby_reload_hint': '已保存。请在「附近的人」点击刷新以应用。',
    'subscribed_plan': '订阅的配对计划',
    'current_account': '当前登入账号',
    'activity_history': '参加活动记录',
    'gender': '性别',
    'purchase_history': '购买记录',
    'purchase_delete_activity_confirm': '确定删除此活动报名记录？',
    'purchase_delete_unpaid_receipt_confirm': '确定删除此条未付款收据？',
    'purchase_activity_receipt_deleted': '已删除此条记录',
    'purchase_activity_receipt_delete_failed': '无法删除，请稍后再试。',
    'follow_instagram': '追踪 Instagram',
    'ad_coop': '广告合作',
    'faq': '常见问题',
    'faq_video_body': '以下为常见问题相关说明视频，点击下方即可在 YouTube 观看。',
    'faq_open_youtube': '打开 YouTube 视频',
    'contact_us': '联络我们',
    'contact_us_whatsapp_action': 'WhatsApp',
    'contact_us_email_label': '电邮',
    'user_terms': '使用者条款',
    'privacy_terms': '隐私条款',
    'privacy_policy_title': '隐私政策',
    'user_terms_title': '使用者条款',
    'user_terms_load_error': '无法载入使用者条款内容，请稍后再试。',
    'privacy_policy_load_error': '无法载入隐私政策内容，请稍后再试。',
    'privacy_settings': '隐私设定',
    'privacy_promo_section': '接收推广及促销',
    'privacy_direct_marketing': '同意直接促销',
    'privacy_direct_marketing_footnote': '选择同意直接促销即代表你同意我们使用你的个人资料联络你以进行促销用途',
    'ad_post_requirement': '广告合作刊登要求：30字内可加图或link',
    'ad_fee_plan_title': '广告刊登收费方案',
    'choose_subscription': '刊登广告项目',
    'months': '个月',
    'subscription_terms':
        '定期扣款，可随时取消，不设退款！透过 iTunes 帐户，Apple Store 或 Google Play 等完成交易，订阅生效后将于到期日 24 小时前以相同价钱自动续订，直至取消。同意使用者条款及隐私条款。',
    'continue': '继续',
    'ad_post': '广告刊登内容',
    'ad_post_image': '图',
    'ad_post_title': '标题',
    'ad_post_link': '可插入 link',
    'ad_post_content': '内容30字内',
    'ad_post_content_heading': '广告刊登内容',
    'submit': '提交',
    'ad_post_record': '广告刊登记录',
    'ad_need_admin_approval': '广告刊登内容发布后需经平台管理员审核通过才会发布。',
    'ad_coop_firebase_not_ready': '无法同步：Firebase 尚未就绪，请稍后再试。',
    'ad_coop_login_required_sync': '请先登录会员账户后再提交，刊登内容才会同步至管理员审核。',
    'ad_coop_order_sync_failed': '无法写入广告订单，已改为「仅贴文」同步；若持续失败请联系客服。',
    'admin_ad_coop_submitted_at': '提交时间',
    'ad_post_submit_snackbar': '广告内容已提交，待管理员审核～',
    'approved': '通过',
    'not_approved': '不通过',
    'pending_review': '待审核',
    'no_ad_posts': '暂无广告刊登记录',
    'ad_post_record_section_content': '刊登内容',
    'ad_post_record_section_orders': '订单与付款',
    'ad_post_record_archived': '历史版本',
    'ad_post_record_cloud': '已同步',
    'btn_edit': '修改',
    'ad_post_edit_title': '修改广告刊登内容',
    'ad_post_delete_confirm': '确定删除此贴文？此操作无法复原。',
    'ad_coop_history_deleted': '已删除此条已同步记录。',
    'ad_post_remove_image': '移除图片',
    'cancel': '取消',
    'subscribed_plan_content': '订阅方案计划内容',
    'subscribed_plan_tier_sync_hint': '此为账户订阅层级同步显示（尚无订单文件时）；完成付款后会显示订单明细。',
    'upgrade_matching_action': '升级配对',
    'subscribed_plan_tier_badge': '层级',
    'subscribed_plan_upgrade_section_body':
        '与订阅方案页相同：开启后可查看、修改每条问题与答案，保存后与后台「升级配对资料库」同步。',
    'subscription_fee': '费用',
    'subscription_date': '订阅日期',
    'expiration_date': '失效日期',
    'auto_renewal': '自动续约',
    'enable_auto_renewal': '启动自动续约',
    'no_subscription_records': '暂无已付费订阅纪录',
    'receipt_title': '收据',
    'payment_type_subscription': '订阅方案',
    'payment_type_ad_coop': '广告合作',
    'ad_coop_unpaid_order_delete_confirm': '确定删除此笔未付款广告合作订单？',
    'ad_coop_unpaid_order_deleted': '已删除订单',
    'ad_coop_unpaid_order_delete_failed': '无法删除，请稍后再试。',
    'payment_type_activity': '活动报名',
    'payment_item': '付款项目',
    'payment_receipt_content': '内容',
    'payment_amount': '金额',
    'payment_date': '日期时间',
    'payment_method': '付款方式',
    'no_purchase_records': '暂无购买记录',
    'payment_method_unknown': '—',
    'payment_method_stripe': '已停用旧制网上付款',
    'payment_method_legacy_removed': '已停用旧制网上付款',
    'payment_method_manual_transfer': 'FPS／微信／银行转账',
    'payment_method_iap_app_store': 'App Store 内购买',
    'payment_method_iap_google_play': 'Google Play 内购买',
    'payment_method_iap_other': '应用内购买',
    'payment_method_iap_demo': '请使用 iOS／Android App 完成应用内购买',
    'payment_success_check_receipt': '付款已成功，请去设置页面查看收据。',
    'payment_status': '付款状态',
    'payment_status_paid': '已付款',
    'payment_status_unpaid': '未付款',
    'payment_method_local_only': '本机记录',
    'activity_content': '活动内容',
    'no_activity_records': '暂无已付费活动记录',
    'event_proposal': '提议活动方案',
    'login_banner': '品牌图像',
    'login_banner_upload': '上传品牌图',
    'login_banner_upload_hint': '平台管理员可上传图片，会显示于启动页、登入页顶部，以及主分页顶栏左侧缩图',
    'login_banner_intro': '平台管理员可分别上传「启动页」与「登入页」图像。主分页顶栏左侧缩图会使用登入页图像。',
    'splash_banner_title': '启动页图像',
    'splash_banner_hint': '显示于 App 启动画面中央',
    'splash_banner_upload': '上传启动页图像',
    'login_page_banner_title': '登入页图像',
    'login_page_banner_hint': '显示于登入页顶部；主分页顶栏左侧缩图亦使用此图',
    'login_page_banner_upload': '上传登入页图像',
    'click_to_upload': '点击上传',
    'restore_default': '还原为默认',
    'banner_saved_splash': '已更新启动页图像',
    'banner_saved_login': '已更新登入页图像',
    'banner_cleared_splash': '启动页已还原为默认图形',
    'banner_cleared_login': '登入页已还原为默认图形',
    'banner_lock_switch': '锁定图像（锁定后无法上传、保存或删除）',
    'banner_locked_notice': '此图像已锁定，请先关闭锁定后再变更',
    'admin_login_title': '管理员登录',
    'admin_account_label': '账号',
    'admin_login_error': '账号或密码错误',
    'admin_login_roster_no_hash': '该账号尚未设置名册登录密码，请由已登录管理员在列表「重置密码」为您设置。',
    'admin_sign_in': '登录',
    'admin_remember_credentials': '记住账号及密码',
    'admin_forgot_password_link': '忘记密码',
    'admin_forgot_password_body': '若忘记密码，请联系系统管理员重置。应用内无法自行重置，请勿向他人泄露账号密码。',
    'admin_settings_title': '管理员设置',
    'admin_settings_intro': '设置后台登录账号与密码。保存后立即生效，请妥善保管。',
    'admin_credentials_saved': '已保存管理员账号密码',
    'admin_credentials_empty': '请输入账号与密码',
    'admin_restore_defaults': '还原默认账号密码',
    'admin_restored_defaults': '已还原为默认账号密码',
    'btn_save': '保存',
    'btn_delete': '删除',
    'admin_delete_order_confirm': '确定删除此笔订单？',
    'admin_logout': '登出',
    'admin_hub_title': '管理后台',
    'admin_pagination_prev': '上一页',
    'admin_pagination_next': '下一页',
    'admin_pagination_summary': '共 {count} 条 · 第 {current} / {total} 页',
    'admin_firebase_required':
        '无法读写后台数据：请确认 Firebase 已初始化，且管理员已用 Firebase Email／密码建立连接。',
    'admin_firebase_retry': '重新连接',
    'admin_backend_firebase_not_ready': 'Firebase 尚未初始化，后台无法连接数据库。请刷新页面或检查网络。',
    'admin_backend_auth_failed':
        '后台无法建立 Firebase 登录。请确认 Firebase 已启用「Email／密码」，并在 Authentication 建立与下方 Email 相同、密码与管理员密码相同的用户。',
    'admin_backend_auth_admin_restricted':
        'Firebase 返回「admin-restricted-operation」。请检查：① Authentication → 设置 →「已授权网域」已加入本站域名。② App Check 强制验证是否拦截 Web。③ Users 已添加管理员 Email 且密码一致。',
    'admin_backend_auth_operation_not_allowed':
        'Firebase 未启用 Email／密码（operation-not-allowed）。请到 Firebase Console → Authentication → Sign-in method → 启用「Email／密码」。',
    'admin_backend_auth_dialog_title': '后台 Firebase 登录说明',
    'admin_backend_auth_user_not_found':
        'Firebase 尚未建立此 Email 帐号：{email}\n\n请到 Firebase Console → Authentication → Users →「添加用户」，Email 请填上列完整字符串，密码须与管理员登录密码相同；并在 Sign-in method 启用「Email／密码」。',
    'admin_backend_auth_wrong_password':
        'Firebase 密码验证失败。请确认 Authentication → Users 内该 Email 的密码与此处相同；或在 Console 重置密码后再试。若构建时使用了 ADMIN_FIREBASE_EMAIL，请与该邮箱一致。',
    'admin_backend_auth_invalid_email':
        'Firebase 不接受的 Email 格式。请检查管理员帐号或联系开发者。',
    'admin_backend_auth_session_expired': '后台登录已过期，请重新登录管理员。',
    'profile_incomplete_title': '个人资料尚未填写完整',
    'profile_incomplete_body':
        '配对需要公开「称呼」、「职业」与「一句话」介绍（一句话不可为系统预设句）。请在「想讲～」页填写称呼、职业与一句话。',
    'profile_incomplete_later': '稍后',
    'profile_incomplete_go_fill': '前往想讲页填写',
    'admin_sec_a': '管理员账户（名册）',
    'admin_sec_b': '会员登记资料',
    'admin_sec_c': '订阅方案订单',
    'admin_sec_d': '升级配对数据库',
    'admin_sec_e': '活动订单',
    'admin_sec_f': '活动',
    'admin_sec_f_editor': '活动编辑',
    'admin_sec_g': '提议活动方案审批',
    'admin_sec_h': '付款方式设置',
    'admin_sec_i': '广告审批通过案例',
    'admin_sec_ad_approval_title': '广告审批',
    'admin_sec_ad_promotion': '宣传贴文',
    'admin_sec_ad_approval_intro': '以下与「广告贴文订单」相同数据来源，供审核会员提交的贴文（文字／图／链接）。',
    'admin_sec_i_approval_section': '广告贴文审批',
    'admin_sec_i_months': '期数（月）',
    'admin_sec_i_amount': '金额（HKD）',
    'admin_sec_i_monthly_orders': '本月广告订单',
    'admin_sec_i_monthly_paid_total': '本月已付款合计',
    'admin_ad_coop_pass': '通过',
    'admin_ad_coop_issue': '有问题',
    'admin_ad_coop_delete_submission_confirm':
        '确定删除此笔提交之广告贴文内容？若有广告合作订单，订单记录仍保留；会员可重新提交贴文。',
    'admin_ad_coop_issue_title': '请填写需修改原因',
    'admin_ad_coop_issue_reason': '原因',
    'admin_ad_coop_issue_required': '请输入原因',
    'admin_ad_coop_review_none': '审核：未标示',
    'admin_ad_coop_review_passed': '审核：已通过',
    'admin_ad_coop_review_pending': '审核：待审／待重审',
    'admin_ad_coop_review_revision': '审核：请修改',
    'admin_ad_coop_image_only_hint': '（仅图片，无文字）',
    'admin_ad_coop_view_content_btn': '查看广告贴文内容',
    'admin_ad_coop_content_dialog_title': '会员提交的广告贴文',
    'admin_ad_coop_content_empty': '尚无文字、图片或链接（请确认会员已于广告合作页提交并同步至订单）。',
    'admin_sec_i_standalone_section': '仅广告贴文（无订单）',
    'admin_sec_ad_approval_records_section': '待审核贴文（会员广告贴文记录）',
    'admin_sec_ad_approval_linked_note':
        '此贴文已同步至会员的广告订单；审核结果会写入订单与通知（本页不显示付款资料）。',
    'admin_ad_approval_publication_heading': '广告刊登内容',
    'admin_sec_i_standalone_note': '此会员尚未建立广告合作订单；可审核贴文内容并通知对方。',
    'admin_ad_promotion_title': '标题',
    'admin_ad_promotion_link': '链接',
    'admin_ad_promotion_content': '内容',
    'admin_ad_promotion_upload': '上传图片',
    'admin_ad_promotion_duration': '发布期限',
    'admin_ad_promotion_publish': '发布',
    'admin_ad_promotion_published': '宣传贴文记录',
    'admin_ad_promotion_empty': '尚未有宣传贴文记录。',
    'admin_ad_promotion_pause': '暂停',
    'admin_ad_promotion_edit': '编辑',
    'admin_ad_promotion_cancel_edit': '取消编辑',
    'admin_ad_promotion_editing_banner': '正在编辑一条贴文；修改后点击下方按钮即可更新并重新发布。',
    'admin_ad_promotion_save_publish': '保存并发布',
    'admin_ad_promotion_updated_ok': '已更新并发布宣传贴文。',
    'admin_ad_promotion_republish': '重新发布',
    'admin_ad_promotion_publish_ok': '已发布宣传贴文。',
    'admin_ad_promotion_publish_failed': '发布失败，请稍后再试。',
    'admin_ad_promotion_paused_ok': '已暂停宣传贴文。',
    'admin_ad_promotion_republish_ok': '已重新发布宣传贴文。',
    'admin_ad_promotion_title_required': '请先填写标题。',
    'admin_ad_promotion_content_required': '请至少填写内容、链接或图片。',
    'admin_ad_promotion_invalid_image': '图片格式不支持或处理失败，请改用 JPG / PNG。',
    'ad_coop_notify_approved': '您的广告贴文内容已通过审核。',
    'ad_coop_notify_revision': '管理员请您修改广告贴文：',
    'ad_coop_notify_dismiss': '关闭',
    'ad_coop_billing_notify_title': '广告刊登通知',
    'admin_sec_j': '广告到期提示',
    'admin_sec_k': '怀疑违规内容',
    'admin_sec_k_empty': '目前没有待审贴文',
    'admin_sec_k_approved': '已批准并发布至邀聊通知',
    'admin_sec_k_rejected': '已拒绝并删除此条待审贴文',
    'admin_sec_k_tab_pending': '待审贴文',
    'admin_sec_k_tab_reports': '会员举报',
    'admin_sec_k_reports_empty': '目前没有待处理举报',
    'admin_report_post_label': '贴文 ID',
    'admin_report_author_label': '作者',
    'admin_report_reason_label': '举报说明',
    'admin_report_ignore': '不理',
    'admin_report_delete_post': '删除贴文',
    'admin_report_warn': '警告',
    'admin_report_blacklist': '加入黑名单',
    'admin_report_ignored': '已标记为不理',
    'admin_report_deleted': '已删除公开贴文',
    'admin_report_warned': '已向会员发出警告（请修改贴文）',
    'admin_report_blacklisted': '已加入黑名单并同步会员账户',
    'moderation_contact_blocked': '内容不得包含电话、电邮、网址或社群联络方式，请修改后再发布。',
    'feed_report_button': '举报',
    'feed_report_title': '举报违规内容',
    'feed_report_hint': '请简述违规情况（例如：骚扰、不当图片、联络方式外泄等）。',
    'feed_report_field_hint': '输入举报内容…',
    'feed_report_submit': '提交',
    'feed_report_cancel': '取消',
    'feed_report_ok': '已提交举报，管理员会跟进。',
    'feed_report_need_login': '请先登录后再举报。',
    'feed_report_empty': '请填写举报说明。',
    'feed_report_fail': '提交失败',
    'moderation_blocked': '内容含有不当用语，无法发布。',
    'moderation_queued': '内容已送交管理员审核，通过后会显示于「邀聊通知」。',
    'moderation_need_login_review': '请先登录会员账户，以便将内容送交管理员审核。',
    'duplicate_same_day': '24 小时内已发布过相同内容，请稍后再试或修改后再发布。',
    'my_posts_header': '已发布的贴文（请避免 24 小时内重复相同内容）：',
    'my_posts_empty': '尚无已发布贴文',
    'post_edit': '修改',
    'post_delete': '删除',
    'post_edit_hint': '输入贴文内容',
    'confirm_delete_post_title': '确定删除此条贴文？',
    'post_deleted': '已删除贴文',
    'post_delete_failed': '删除失败，请稍后再试',
    'post_updated': '已更新贴文',
    'moderation_suspected_edit': '内容需管理员审核后才会更新显示。',
    'load_more_feed': '加载更多',
    'feed_post_image_title': '发布贴文图片',
    'feed_post_image_hint': '与上方消息头像分开；此图会显示于「邀聊通知」贴文（可选）。',
    'feed_post_image_tap': '点击上传',
    'image_moderation_blocked': '图片未通过安全检测（可能为不雅、色情或文件损坏），无法与贴文一并发布。',
    'admin_sec_a_add': '新增名册项',
    'admin_sec_a_new_expand': '新增管理员账户',
    'admin_sec_a_account_name': '管理员账户名称',
    'admin_sec_a_recovery_email': '备用邮箱（重设密码用）',
    'admin_sec_a_password_hint':
        '若填写密码，将用「备用邮箱」在 Firebase 创建账号（须与 Authentication 不重复）。留空则仅写入名册，请稍后在 Console 手动创建用户。',
    'admin_sec_a_set_password': '设置密码（选填）',
    'admin_sec_a_submit': '提交',
    'admin_sec_a_list_title': '现有管理员账户列表',
    'admin_sec_a_col_name': '账户名称',
    'admin_sec_a_col_reset': '更改密码',
    'admin_sec_a_col_recovery': '备用邮箱',
    'admin_sec_a_col_delete': '删除账户',
    'admin_sec_a_col_manual_reset': '重置密码',
    'admin_sec_a_manual_reset_title': '重置名册登录密码',
    'admin_sec_a_manual_reset_hint': '新密码将与管理员登录页的「账号」「密码」一致（账号为左列账户名称）。',
    'admin_sec_a_new_password': '新密码',
    'admin_sec_a_confirm_password': '确认密码',
    'admin_sec_a_password_mismatch': '两次密码不一致',
    'admin_sec_a_manual_reset_submit': '确定',
    'admin_sec_a_manual_reset_ok': '已更新；请用新密码登录后台。',
    'admin_sec_a_change_password': '发送重设邮件',
    'admin_sec_a_reset_sent': '已发送密码重设邮件',
    'admin_sec_a_reset_fail': '发送失败',
    'admin_sec_a_recovery_required': '请先填写备用邮箱',
    'admin_sec_a_required_fields': '请填写账户名称与备用邮箱',
    'admin_sec_a_added': '已新增名册',
    'admin_sec_a_added_no_password': '已加入名册；尚未设置登录密码，请填写「密码」重新提交或由其他管理员「重置密码」。',
    'admin_sec_a_added_shared_email':
        '该备用邮箱已是会员或已有账号，已加入管理员名册（可同时为会员与管理员）。未另建 Firebase 用户；重设密码将发至该邮箱的既有账号。',
    'admin_sec_a_add_fail': '新增失败',
    'admin_sec_a_edit_recovery': '编辑备用邮箱',
    'admin_forgot_enter_account': '请输入账号',
    'admin_forgot_enter_email': '请输入备用邮箱',
    'admin_forgot_submit': '更改密码（发送重设邮件）',
    'admin_forgot_mismatch': '账号与备用邮箱与名册不符',
    'admin_forgot_sent': '若资料正确，已发送重设密码邮件，请查收邮箱。',
    'admin_forgot_firebase': 'Firebase 未就绪，无法验证名册或发信。',
    'admin_forgot_roster_body':
        '管理员后台登录密码保存在「管理员账户」名册。若忘记，请联系其他能登录的管理员，在名册列表为您按「重置密码」设置新密码后即可登录。',
    'admin_forgot_fail': '处理失败',
    'admin_sec_display_name': '显示名称',
    'admin_sec_note': '备注',
    'admin_sec_empty': '暂无数据',
    'admin_sec_deleted': '已删除',
    'admin_sec_b_tab_members': '会员与统计',
    'admin_sec_b_tab_blacklist': '黑名单',
    'admin_sec_b_total': '注册会员总数',
    'admin_sec_b2_add': '加入黑名单',
    'admin_sec_c_add_order': '新增订单',
    'admin_sec_c_monthly': '本月订单数',
    'admin_sec_c_monthly_paid_line': '本月已付款：{amount}',
    'admin_sec_c_renewal_total': '续订总数：{n}',
    'admin_sec_c_expiry_hint': '未来 30 日内到期',
    'admin_sec_c_expires': '到期日',
    'admin_sec_c_plan': '方案代码',
    'admin_sec_c_member': '会员资料',
    'admin_sec_c_order_status': '订单状态',
    'admin_sec_c_deal_done': '成交',
    'admin_sec_c_deal_pending': '未成交',
    'admin_pay_other': '其他',
    'admin_sec_c_receipt_missing': '尚未上传收据',
    'admin_sec_c_mark_paid_needs_receipt': '此付款方式须先有收据图片，方可标记为已付款。',
    'admin_sec_c_pay_state': '付款状态',
    'admin_sec_c_paid': '已付款',
    'admin_sec_c_unpaid': '未付款',
    'admin_sec_c_btn_mark_paid': '已付款',
    'admin_sec_c_receipt': '收据',
    'admin_sec_c_pay_method': '付款方式',
    'admin_sec_c_order_time': '订单时间',
    'admin_pay_manual_fps_wechat_bank': '其他（FPS／微信／银行转账）',
    'admin_pay_other_demo_web': '其他（示范／Web 无法使用商店）',
    'admin_pay_other_demo': '其他（示范）',
    'admin_pay_stripe': '已停用旧制付款',
    'admin_pay_iap_ios': 'App Store（IAP）',
    'admin_pay_iap_android': 'Google Play（IAP）',
    'admin_sec_d_add': '加入配对库',
    'admin_sec_e_criteria': '配对条件（按要求）',
    'admin_sec_e_push': '活动推送通知（写入通知队列）',
    'admin_sec_e_push_btn': '排程推送',
    'admin_sec_e_push_queued': '已写入通知队列',
    'admin_sec_e_activity_orders': '活动订单数目',
    'admin_sec_e_monthly_count': '本月订单：{n} 笔',
    'admin_sec_e_monthly_paid_label': '已付款',
    'admin_sec_e_monthly_paid_total': '本月合计：{amount}',
    'admin_sec_e_activity_empty': '尚无活动报名订单（会员于前台活动页完成报名后会显示）。',
    'admin_sec_e_purged_unpaid': '已自动删除 {n} 笔逾一个月未付款的活动订单。',
    'admin_purge_unpaid_orders_snackbar': '已自动删除 {n} 笔逾一个月未付款的订单（订阅／广告／活动）。',
    'admin_manual_sweep_title': '手动月缴即时检查',
    'admin_manual_sweep_body':
        '按一下即可立即执行手动月缴 sweep，不用等每日排程。系统会即时补发提醒、停权逾期未付款会员，并更新相关订单与会员状态。',
    'admin_manual_sweep_btn': '立即执行 sweep',
    'admin_manual_sweep_running': '执行中…',
    'admin_manual_sweep_done': '已即时执行手动月缴检查，更新 {n} 笔记录。',
    'admin_ad_coop_sweep_done': '已即时执行广告刊登月缴检查，更新 {n} 笔记录。',
    'admin_activity_summary': '活动内容摘要',
    'admin_sec_f_add': '新增活动',
    'admin_sec_f_upload_image': '上传图片',
    'admin_sec_f_images': '图片网址（逗号分隔）',
    'admin_sec_f_payment': '付款说明',
    'admin_sec_f_gmail': 'Gmail 通知（标记，实际发信需 Cloud Functions）',
    'admin_sec_f_price': '价钱',
    'admin_sec_f_activity_detail': '活动详情（报名页）',
    'admin_sec_f_event_poster_upload': '上传活动海报（报名页「了解详情」右上角）',
    'admin_sec_f_view_activity_detail': '显示活动详情',
    'admin_sec_f_remove_event_poster': '移除海报',
    'admin_sec_f_tap_area_to_upload': '点击框内上传图片',
    'admin_sec_f_poster_rules': '仅支持 JPG、PNG；单文件 5MB 内，超过将自动压缩。',
    'admin_sec_f_poster_invalid_format': '请选择 JPG 或 PNG 图片。',
    'admin_sec_f_list_poster_placeholder': '图片',
    'admin_sec_f_activity_detail_hint': '显示于活动标题下方，例如流程、地点、注意事项',
    'admin_sec_f_body_hint': '列表与同步用正文；若未填「价钱」，第一行可作价钱显示（旧版兼容）。',
    'admin_sec_f_activity_dates_title': '活动日期',
    'admin_sec_f_activity_dates_hint':
        '可添加多个不同日期；会员在报名页可横向滑动选择。留空则不显示日期选择。',
    'admin_sec_f_activity_dates_add': '添加日期栏',
    'admin_sec_f_activity_date_placeholder': '例：2025年6月14日（六）',
    'admin_sec_f_registration_cap': '报名人数（参加者单次可选 1～10 人；不设活动总报名上限）',
    'pay_choice_iap': 'App Store／Google Play',
    'pay_choice_stripe': '已停用旧制网上付款',
    'pay_choice_manual': 'FPS／微信／银行户口',
    'payment_manual_orange_hint_above': '按下面橙键付款',
    'subscription_iap_subtitle': '依设备使用 App Store 或 Google Play 付款',
    'subscription_stripe_subtitle': '此付款方式已停用',
    'subscription_manual_subtitle': '按上面橙键进行付款',
    'activity_details_label': '活动详情',
    'activity_reg_event_date': '活动日期',
    'activity_reg_pick_event_date': '选择活动日期',
    'activity_reg_swipe_right_select_gt': '向右滑动选择》',
    'activity_reg_swipe_right_select': '向右滑动选择',
    'activity_tap_image_enlarge': '按图放大',
    'activity_scroll_pay_banner': '向下滑动付款完成报名',
    'activity_scroll_down_hint': '向下滑动',
    'activity_reg_headcount': '报名人数',
    'activity_choose_payment': '付款方式',
    'activity_payment_tap_hint': '按上面橙键进行付款',
    'activity_login_required': '请先登录一般会员账户（勿使用访客）以报名及付款。',
    'activity_order_failed': '无法建立订单，请确认已登录或网络正常。',
    'activity_stripe_url_missing': '此旧制网上付款方式已停用。',
    'activity_order_manual_snackbar': '已提交活动报名订单，请于 WhatsApp 发送收据。',
    'activity_whatsapp_prefill': '我想报名活动：',
    'activity_whatsapp_prefill_tail': ' 位，总额 ',
    'activity_iap_demo_snackbar': '（示范）已记录活动报名。',
    'activity_iap_use_app': '应用内购买请使用 iOS／Android App 完成。',
    'admin_sec_f_saving': '保存中…',
    'admin_sec_f_sync_failed': '活动已写入后台，但同步至前台活动列表失败：{error}。请检查网络或刷新活动页。',
    'admin_sec_f_empty_hint':
        '点右下角「新增活动」；填写名称、活动详情（报名页）、报名人数、价钱与付款方式后按「保存」会同步至前台活动页。',
    'admin_sec_f_title_required': '请输入活动名称',
    'admin_sec_f_delete_confirm': '确定删除此活动？此操作无法复原。',
    'admin_sec_g_emails': '报告收件人 Email（逗号分隔）',
    'admin_sec_g_cadence': '报告频率',
    'admin_sec_g_monthly': '每月',
    'admin_sec_g_weekly': '每周',
    'admin_sec_h_new': '新增测试申请',
    'admin_sec_company': '公司／名称',
    'admin_sec_contact': '联系方式',
    'admin_sec_approve': '通过',
    'admin_sec_reject': '拒绝',
    'admin_sec_reject_reason': '拒绝原因（必填）',
    'admin_sec_h_approved': '已通过',
    'admin_sec_j_empty': '14 日内无即将到期之已核准广告',
    'admin_sec_j_expires': '到期日',
    'admin_field_uid': '会员 UID',
    'admin_field_reason': '原因',
    'admin_sec_saved': '已保存',
    'admin_save_failed': '保存失败',
    'admin_src_a':
        'Firestore「admin_accounts」：后台管理员名册（与 App 内本地管理员账号密码分开）。字段：displayName、note、active、createdAt。',
    'admin_src_b':
        '「users」：注册/登录与个人档同步（memberNo、email、displayName、phone、gender、age、subscriptionActive、tags、sentence、avatar、updatedAt）。「user_blacklist」：按 UID 封禁。',
    'admin_src_c':
        '「subscription_orders」：后台补登订单；「payments」「subscriptions」：App／IAP 与历史付款资料记录。',
    'admin_src_d':
        '「upgrade_matching_pool」：升级配对候选；可从 users.subscriptionActive＝true 同步。另见「matches」互配、「users」探索。',
    'admin_src_e':
        '「match_admin_settings」：配对条件；「notifications」type=admin_event：推送队列（FCM 需 Cloud Functions）。',
    'admin_src_f': '「event_cms」：后台活动文案；App 活动列表为「activities」。',
    'admin_src_g': '「event_proposals」：会员提议之活动方案；管理员可标示通过或落选（status）。',
    'admin_src_h':
        '「ad_partner_requests」status=pending：审批中（拒绝须填 rejectReason）。',
    'admin_src_i': '同集合 status=approved：审批通过案例。',
    'admin_src_j': '同集合 approved 且 expiresAt 将届：到期提示。',
    'admin_sec_c_app_records': 'App 付款／订阅集合（只读预览）',
    'admin_sec_d_sync': '同步订阅中会员至配对库',
    'admin_sec_d_sync_ok': '已同步',
    'admin_sec_member_no': '会员编号',
    'admin_sec_b_reg_date': '登记日期',
    'admin_sec_b_add_blacklist': '加入黑名单',
    'admin_sec_b2_checkbox_reason': '后台名单勾选',
    'admin_sec_subscribed': '已订阅',
    'admin_sec_b_cleanup_scan': '扫描并删除资料不齐占位',
    'admin_sec_b_cleanup_title': '删除占位配对资料',
    'admin_sec_b_cleanup_body':
        '将删除「users」中：职业为「未填写」且个人句仍为系统默认句的账号。单次最多扫描 500 笔 job=未填写。会排除您当前 Firebase 登录的 UID。',
    'admin_sec_b_cleanup_found': '符合条件',
    'admin_sec_b_cleanup_confirm': '确认删除',
    'admin_sec_b_cleanup_done': '已删除',
    'admin_sec_b_cleanup_none': '没有符合条件的占位会员',
    'admin_sec_b_cleanup_unit': '笔',
    'event_proposal_record': '提议活动方案记录',
    'event_name': '活动名称',
    'event_promo_image': '活动宣传图片',
    'event_promo_upload_whatsapp_hint': '上传活动宣传图片，请按左边WhatsApp上传～',
    'event_content': '活动内容',
    'event_venue': '举行的地方',
    'event_date': '日期',
    'event_time': '时间',
    'event_cost': '活动成本价',
    'event_proposal_note': '阁下提议活动方案一经被采纳，可免费参加其活动一次',
    'event_content_placeholder': '地方、日期、时间',
    'adopted': '采纳',
    'not_adopted': '不采纳',
    'event_proposal_status_passed': '通过',
    'event_proposal_status_rejected': '落选',
    'event_proposal_edit_mode': '修改提议',
    'event_proposal_delete_confirm': '确定删除此提议记录？此操作无法复原。',
    'event_proposal_duplicate': '提议内容与已有记录重复，请修改后再提交。',
    'event_proposal_submit_failed': '无法提交：请确认已登录且网络正常，稍后再试。',
    'event_proposal_login_required':
        '无法提交：请检查网络；若仍失败，请在 Firebase 控制台启用「匿名」登录方式。',
    'event_proposal_timeout': '提交超时（常见于图片过大或网络慢）。请换较小图片或稍后再试。',
    'event_proposal_record_modify': '修改',
    'event_proposal_image_failed': '图片上传失败（常见原因：存储权限未开放）。请重试或联系管理员。',
    'storage_upload_anonymous_no_image':
        '匿名登录无法上传图片至云端存储。请改用 Email／Google／Apple 登录后再试。',
    'no_event_proposals': '暂无提议活动方案记录',
    'chat_quota_free_hint':
        '每日最多可免费向 2 位「不同会员」各发消息（不限条数）；与同人同日继续聊不另计。管理员确认已付款后，订阅生效者可无限次与不同会员聊天。',
    'chat_quota_paywall':
        '每日免费只能与两位会员聊天，请成功订阅方案后，不限次数与其他会员进行聊天。',
    'chat_quota_dialog_title': '免费聊天名额已满',
    'chat_quota_go_subscribe': '请订阅方案',
    'messaging_requires_invite_accept': '请先邀请对方，待对方于「邀聊通知」接受后才可进入消息聊天。',
    'heart_counter_invite_followup': '已记录互相关注。请发起邀聊，对方接受后即可进入消息页面聊天。',
    'match_mutual_invite_body': '你和对方互相喜欢！请发出邀聊，对方接受后即可进入消息页面聊天。',
    'send_chat_invitation': '发出邀聊',
    'chat_invite_interest_body': '有人对你的资料有兴趣，想与对方聊天吗？',
    'chat_invite_btn_want': '接受',
    'chat_invite_btn_decline': '拒绝',
    'chat_invite_popup_title': '邀聊通知',
    'chat_invite_popup_agree': '同意',
    'chat_invite_popup_reject': '拒绝',
    'chat_invite_accept_failed_missing':
        '找不到此邀请，可能尚未同步或被撤回，请下拉重新载入。',
    'chat_invite_accept_failed_already':
        '此邀请已处理（可能已在其他设备接受），请下拉重新载入。',
    'chat_invite_accept_failed_unknown': '无法接受邀请，请稍后再试。',
  };

  // 英文字典
  final Map<String, String> _en = {
    'app_name': 'Fast Dating',
    'login': 'Login/Register',
    'phone': 'Phone Number',
    'password': 'Password',
    'send_code': 'Send Code',
    'signup_email_verification': 'Email verification',
    'signup_email_code_hint': '6-digit code',
    'signup_get_code': 'Get code',
    'signup_code_sent': 'Verification code sent. Check your email.',
    'signup_verify': 'Verify',
    'signup_email_verified': '✓ Email verified',
    'signup_need_verify': 'Please verify your email first',
    'signup_err_invalid_email': 'Enter a valid email address',
    'signup_err_send_cooldown': 'Too many requests. Please wait a moment',
    'signup_err_email_send_failed': 'Could not send the email. Try again later',
    'signup_err_resend_unauthorized':
        'Resend API key is invalid. Update RESEND_API_KEY and redeploy.',
    'signup_err_resend_domain':
        'Sender domain is not verified in Resend. Verify your domain and set RESEND_FROM in cloud config.',
    'signup_err_resend_test_recipient':
        'Resend test mode: only certain recipients are allowed. Add a test address in the Resend dashboard, or verify your domain and From address.',
    'signup_err_email_delivery_not_configured':
        'Email delivery is not fully set up yet. Try again later or contact us.',
    'signup_err_wrong_code': 'Incorrect code',
    'signup_err_otp_expired': 'Code expired. Request a new one',
    'signup_err_no_otp_request': 'Tap “Get code” first',
    'signup_err_email_not_verified': 'Please verify your email first',
    'signup_err_gate_expired': 'Verification window expired. Get a new code',
    'signup_err_email_in_use': 'This email is already registered',
    'signup_err_weak_password': 'Password must be at least 6 characters',
    'signup_err_name_too_short': 'Login name needs at least 4 characters',
    'signup_err_create_failed': 'Sign up failed. Please try again',
    'signup_err_no_firebase': 'Not connected. Sign-up unavailable',
    'forgot_pwd': 'Forgot Password',
    'register': 'Register',
    'home': 'Home',
    'message': 'Message',
    'message_list_guest_hint': 'Sign in to view messages',
    'message_guest_dm_and_feed_hint':
        'Sign in to see private chats. Promotional posts below are shown to everyone, same as on the website.',
    'message_page_free_chat_quota_tip':
        'Non-subscribers: chat for free with up to two different members per calendar day.',
    'profile': 'Profile',
    'settings': 'Settings',
    'nearby': 'Nearby',
    'menu': 'Menu',
    'file': 'Profile',
    'publish': 'Chat invites',
    'publish_feed_empty_hint':
        'No posts match the filters yet. Pull down to refresh, or tap below to reload site-wide announcements.',
    'publish_feed_retry': 'Reload feed',
    'publish_invites_section_heading': 'Chat messages',
    'publish_invites_section_intro':
        'Invites sent from the home page appear here. You can decline or accept.',
    'thinking_prompt': 'What are you thinking?',
    'one_sentence': 'One sentence',
    'gift_shop': 'Gift shop',
    'chat': 'Chat',
    'subscription_plan': 'Subscription Plan',
    'language': 'Language',
    'font_size': 'Font size',
    'font_size_small': 'Small',
    'font_size_medium': 'Medium',
    'font_size_large': 'Large',
    'font_size_small_short': 'A',
    'font_size_large_short': 'A+',
    'notification': 'Notification',
    'notif_settings_title': 'Notification settings',
    'notif_section_background': 'Background notifications',
    'notif_heart_enabled': 'Heart notifications',
    'notif_new_message_sound': 'New message notifications',
    'display': 'Display',
    'account': 'Account',
    'about': 'About Fast Dating',
    'terms': 'Terms & Conditions',
    'logout': 'Logout',
    'delete_account': 'Delete Account',
    'region': 'Region',
    'show_gender': 'Show My Gender',
    'show_on_platform': 'Show Me on Fast Dating',
    'tags': 'Tags',
    'filter': 'Filter',
    'age_range': 'Age Range',
    'show_other_gender': 'Show Other Gender',
    'male': 'Male',
    'female': 'Female',
    'interest': 'Interest',
    'distance': 'Distance',
    'like': 'Like',
    'pass': 'Pass',
    'match_success': 'Match Success!',
    'chat_now': 'Chat Now',
    'close': 'Close',
    'home_first_tip_body':
        'Use the One sentence button at the bottom right to complete your profile, then tap Start chatting.',
    'nearby_top_tip_body':
        'If you have not used One sentence on Home to fill in your details, tap One sentence at the bottom right to complete them, then set filters to find people to chat with.',
    'nearby_demo_chat_hint': NearbyDemoStrings.en,
    'cookie_banner_title': 'Cookies & privacy',
    'cookie_banner_body':
        'We use essential cookies (including a secure login session set by the server) for account safety, and may store language and display preferences. If you accept analytics, we record anonymized page-view summaries (no chat text or passwords) to improve matching.',
    'cookie_accept_essential': 'Essential only',
    'cookie_accept_all': 'Accept analytics',
    'cookie_rechoose': 'Change cookie preferences',
    'lang_zh_tw': 'Traditional',
    'lang_zh_cn': 'Simplified',
    'lang_en': 'English',
    'notification_settings': 'Notification',
    'inappropriate_filter': 'Inappropriate filter',
    'location_for_nearby': 'Location (Nearby)',
    'location_for_nearby_hint':
        'When on, GPS is used and coordinates are sent to the server for real nearby results. When off, the list loads without your position.',
    'location_fetch_failed': 'Could not get location. Loaded without GPS.',
    'location_nearby_reload_hint':
        'Saved. Open Nearby and tap refresh to apply.',
    'subscribed_plan': 'Subscribed plan',
    'current_account': 'Current account',
    'activity_history': 'Activity history',
    'gender': 'Gender',
    'purchase_history': 'Purchase history',
    'purchase_delete_activity_confirm': 'Delete this activity signup record?',
    'purchase_delete_unpaid_receipt_confirm': 'Delete this unpaid receipt?',
    'purchase_activity_receipt_deleted': 'Record removed',
    'purchase_activity_receipt_delete_failed': 'Could not delete. Try again.',
    'follow_instagram': 'Follow Instagram',
    'ad_coop': 'Ad cooperation',
    'faq': 'FAQ',
    'faq_video_body':
        'Here is a short video with answers to common questions. Tap below to watch on YouTube.',
    'faq_open_youtube': 'Open on YouTube',
    'contact_us': 'Contact us',
    'contact_us_whatsapp_action': 'WhatsApp',
    'contact_us_email_label': 'Email',
    'user_terms': 'User terms',
    'privacy_terms': 'Privacy terms',
    'privacy_policy_title': 'Privacy policy',
    'user_terms_title': 'User terms',
    'user_terms_load_error':
        'Could not load the user terms. Please try again later.',
    'privacy_policy_load_error':
        'Could not load the privacy policy. Please try again later.',
    'privacy_settings': 'Privacy settings',
    'privacy_promo_section': 'Promotions & marketing',
    'privacy_direct_marketing': 'Agree to direct marketing',
    'privacy_direct_marketing_footnote':
        'If you turn this on, you agree that we may use your personal data to contact you for promotional purposes.',
    'ad_post_requirement':
        'Ad cooperation: max 30 characters; optional image or link',
    'ad_fee_plan_title': 'Ad publication fee plan',
    'choose_subscription': 'Ad placement options',
    'months': ' months',
    'subscription_terms':
        'Regular deductions, can cancel anytime, no refunds! Complete the transaction via your iTunes account, Apple App Store or Google Play, etc. Subscription auto-renews 24h before expiry at the same price until cancelled. Agree to User Terms and Privacy Policy.',
    'continue': 'Continue',
    'ad_post': 'Ad publication content',
    'ad_post_image': 'Image',
    'ad_post_title': 'Title',
    'ad_post_link': 'Insert link',
    'ad_post_content': 'Content (max 30 chars)',
    'ad_post_content_heading': 'Ad publication content',
    'submit': 'Submit',
    'ad_post_record': 'Ad publication record',
    'ad_need_admin_approval':
        'Published ad content requires platform admin approval before going live.',
    'ad_coop_firebase_not_ready':
        'Cannot sync: Firebase is not ready. Please try again.',
    'ad_coop_login_required_sync':
        'Please sign in with a member account before submitting so admins can review your ad.',
    'ad_coop_order_sync_failed':
        'Could not update the ad order; submitted as a standalone post instead. Contact support if this persists.',
    'admin_ad_coop_submitted_at': 'Submitted at',
    'ad_post_submit_snackbar': 'Ad content submitted. Pending admin review.',
    'approved': 'Approved',
    'not_approved': 'Rejected',
    'pending_review': 'Pending',
    'no_ad_posts': 'No ad publication records yet',
    'ad_post_record_section_content': 'Published content',
    'ad_post_record_section_orders': 'Orders & payment',
    'ad_post_record_archived': 'Previous version',
    'ad_post_record_cloud': 'Synced',
    'btn_edit': 'Edit',
    'ad_post_edit_title': 'Edit ad publication content',
    'ad_post_delete_confirm': 'Delete this post? This cannot be undone.',
    'ad_coop_history_deleted': 'This synced record has been removed.',
    'ad_post_remove_image': 'Remove image',
    'cancel': 'Cancel',
    'subscribed_plan_content': 'Subscription plan content',
    'subscribed_plan_tier_sync_hint':
        'Synced from your account tier when no order document exists yet.',
    'upgrade_matching_action': 'Upgrade matching',
    'subscribed_plan_tier_badge': 'Tier',
    'subscribed_plan_upgrade_section_body':
        'Same as the subscription tab: open to view or edit every question and answer; saving syncs with the admin upgrade-matching pool.',
    'subscription_fee': 'Fee',
    'subscription_date': 'Subscription date',
    'expiration_date': 'Expiration date',
    'auto_renewal': 'Auto renewal',
    'enable_auto_renewal': 'Enable auto renewal',
    'no_subscription_records': 'No paid subscription records yet',
    'receipt_title': 'Receipt',
    'payment_type_subscription': 'Subscription',
    'payment_type_ad_coop': 'Ad posts',
    'ad_coop_unpaid_order_delete_confirm':
        'Delete this unpaid ad cooperation order?',
    'ad_coop_unpaid_order_deleted': 'Order deleted',
    'ad_coop_unpaid_order_delete_failed': 'Could not delete. Try again later.',
    'payment_type_activity': 'Event signup',
    'payment_item': 'Item',
    'payment_receipt_content': 'Details',
    'payment_amount': 'Amount',
    'payment_date': 'Date & time',
    'payment_method': 'Payment method',
    'no_purchase_records': 'No purchase records yet',
    'payment_method_unknown': '—',
    'payment_method_stripe': 'Legacy web payment (disabled)',
    'payment_method_legacy_removed': 'Legacy web payment (disabled)',
    'payment_method_manual_transfer': 'FPS / WeChat / bank transfer',
    'payment_method_iap_app_store': 'App Store in-app purchase',
    'payment_method_iap_google_play': 'Google Play in-app purchase',
    'payment_method_iap_other': 'In-app purchase',
    'payment_method_iap_demo':
        'Complete in-app purchase in the iOS or Android app',
    'payment_success_check_receipt':
        'Payment successful. Please open Settings to view your receipt.',
    'payment_status': 'Payment status',
    'payment_status_paid': 'Paid',
    'payment_status_unpaid': 'Unpaid',
    'payment_method_local_only': 'On-device only',
    'activity_content': 'Activity content',
    'no_activity_records': 'No paid activity records yet',
    'event_proposal': 'Suggest Event Proposal',
    'login_banner': 'Brand images',
    'login_banner_upload': 'Upload brand image',
    'login_banner_upload_hint':
        'Admins can upload an image. It appears on the splash screen, login header, and the main tab bar (leading thumbnail)',
    'login_banner_intro':
        'Admins can upload splash and login images separately. The main tab bar thumbnail uses the login image.',
    'splash_banner_title': 'Splash screen image',
    'splash_banner_hint': 'Shown on the app splash screen',
    'splash_banner_upload': 'Upload splash image',
    'login_page_banner_title': 'Login page image',
    'login_page_banner_hint':
        'Shown on the login header; the main tab bar thumbnail uses this image too',
    'login_page_banner_upload': 'Upload login page image',
    'click_to_upload': 'Tap to upload',
    'restore_default': 'Restore default',
    'banner_saved_splash': 'Splash image updated',
    'banner_saved_login': 'Login page image updated',
    'banner_cleared_splash': 'Splash image restored to default',
    'banner_cleared_login': 'Login page image restored to default',
    'banner_lock_switch':
        'Lock image (no upload, save, or delete while locked)',
    'banner_locked_notice':
        'This image is locked. Turn off the lock to make changes.',
    'admin_login_title': 'Admin sign in',
    'admin_account_label': 'Account',
    'admin_login_error': 'Invalid account or password',
    'admin_login_roster_no_hash':
        'No roster password set yet. Ask a logged-in admin to use “Reset password” in the directory.',
    'admin_sign_in': 'Sign in',
    'admin_remember_credentials': 'Remember account and password',
    'admin_forgot_password_link': 'Forgot password',
    'admin_forgot_password_body':
        'If you forgot your password, ask your system administrator to reset it. In-app self-service reset is not available. Do not share your credentials.',
    'admin_settings_title': 'Admin settings',
    'admin_settings_intro':
        'Set the admin sign-in account and password. Changes apply immediately. Keep them safe.',
    'admin_credentials_saved': 'Admin credentials saved',
    'admin_credentials_empty': 'Please enter account and password',
    'admin_restore_defaults': 'Restore default credentials',
    'admin_restored_defaults': 'Restored to default credentials',
    'btn_save': 'Save',
    'btn_delete': 'Delete',
    'admin_delete_order_confirm': 'Delete this order?',
    'admin_logout': 'Log out',
    'admin_hub_title': 'Admin console',
    'admin_pagination_prev': 'Previous',
    'admin_pagination_next': 'Next',
    'admin_pagination_summary': '{count} items · page {current} / {total}',
    'admin_firebase_required':
        'Cannot access admin data: ensure Firebase is initialized and the admin signed in with Firebase Email/Password.',
    'admin_firebase_retry': 'Reconnect',
    'admin_backend_firebase_not_ready':
        'Firebase is not initialized; admin database is unavailable. Refresh the page or check your network.',
    'admin_backend_auth_failed':
        'Could not sign in to Firebase for admin. Enable Email/Password in Firebase Authentication and create a user with the Email below and the same password as the admin login.',
    'admin_backend_auth_admin_restricted':
        'Firebase returned admin-restricted-operation. Check: authorized domains include your site; App Check for Web if enforced; admin user exists in Authentication with matching password.',
    'admin_backend_auth_operation_not_allowed':
        'Email/Password is disabled (operation-not-allowed). Enable it in Firebase Console → Authentication → Sign-in method.',
    'admin_backend_auth_dialog_title': 'Admin Firebase sign-in',
    'admin_backend_auth_user_not_found':
        'No Firebase user for Email: {email}\n\nIn Firebase Console → Authentication → Users, add a user with this exact Email and the same password as the admin login; enable Email/Password sign-in.',
    'admin_backend_auth_wrong_password':
        'Firebase rejected the password. In Authentication → Users, reset that Email’s password to match this screen, or align with ADMIN_FIREBASE_EMAIL if you built with it.',
    'admin_backend_auth_invalid_email':
        'Invalid Email format for Firebase. Check the admin login or contact the developer.',
    'admin_backend_auth_session_expired':
        'Admin session expired. Please sign in again.',
    'profile_incomplete_title': 'Profile incomplete',
    'profile_incomplete_body':
        'Matching needs your display name, job, and a personal sentence (not the default). Fill them on the 「想講～」 page.',
    'profile_incomplete_later': 'Later',
    'profile_incomplete_go_fill': 'Open 想講 page',
    'admin_sec_a': 'Admin accounts (directory)',
    'admin_sec_b': 'Member registration',
    'admin_sec_c': 'Subscription orders',
    'admin_sec_d': 'Upgrade matching pool',
    'admin_sec_e': 'Activity orders',
    'admin_sec_f': 'Activities',
    'admin_sec_f_editor': 'Edit activities',
    'admin_sec_g': 'Event proposal review',
    'admin_sec_h': 'Payment method settings',
    'admin_sec_i': 'Ad post orders',
    'admin_sec_ad_approval_title': 'Ad approval',
    'admin_sec_ad_promotion': 'Promotion posts',
    'admin_sec_ad_approval_intro':
        'Same data as 「Ad post orders」—review member-submitted ad text, images, and links.',
    'admin_sec_i_approval_section': 'Ad post content review',
    'admin_sec_i_months': 'Duration (months)',
    'admin_sec_i_amount': 'Amount (HKD)',
    'admin_sec_i_monthly_orders': 'Orders this month',
    'admin_sec_i_monthly_paid_total': 'Paid total (this month)',
    'admin_ad_coop_pass': 'Approve',
    'admin_ad_coop_issue': 'Needs changes',
    'admin_ad_coop_delete_submission_confirm':
        'Delete this submitted ad post content? Any ad cooperation order record stays; the member can submit again.',
    'admin_ad_coop_issue_title': 'Reason for revision',
    'admin_ad_coop_issue_reason': 'Reason',
    'admin_ad_coop_issue_required': 'Please enter a reason',
    'admin_ad_coop_review_none': 'Review: none',
    'admin_ad_coop_review_passed': 'Review: approved',
    'admin_ad_coop_review_pending': 'Review: pending',
    'admin_ad_coop_review_revision': 'Review: revision requested',
    'admin_ad_coop_image_only_hint': '(Image only, no text)',
    'admin_ad_coop_view_content_btn': 'View ad post content',
    'admin_ad_coop_content_dialog_title': 'Submitted ad post',
    'admin_ad_coop_content_empty':
        'No text, image, or link yet. Ensure the member submitted on Ad cooperation and it synced to the order.',
    'admin_sec_i_standalone_section': 'Ad post only (no order)',
    'admin_sec_ad_approval_records_section':
        'Pending ad posts (member ad post records)',
    'admin_sec_ad_approval_linked_note':
        'This post is linked to the member’s ad order; review updates the order and notifications (no payment details here).',
    'admin_ad_approval_publication_heading': 'Ad publication content',
    'admin_sec_i_standalone_note':
        'This member has no ad cooperation order yet; review the post and notify them.',
    'admin_ad_promotion_title': 'Title',
    'admin_ad_promotion_link': 'Link',
    'admin_ad_promotion_content': 'Content',
    'admin_ad_promotion_upload': 'Upload image',
    'admin_ad_promotion_duration': 'Publish duration',
    'admin_ad_promotion_publish': 'Publish',
    'admin_ad_promotion_published': 'Promotion post records',
    'admin_ad_promotion_empty': 'No promotion post records yet.',
    'admin_ad_promotion_pause': 'Pause',
    'admin_ad_promotion_edit': 'Edit',
    'admin_ad_promotion_cancel_edit': 'Cancel editing',
    'admin_ad_promotion_editing_banner':
        'Editing a post; tap the button below to save and publish changes.',
    'admin_ad_promotion_save_publish': 'Save & publish',
    'admin_ad_promotion_updated_ok': 'Promotion post updated and published.',
    'admin_ad_promotion_republish': 'Republish',
    'admin_ad_promotion_publish_ok': 'Promotion post published.',
    'admin_ad_promotion_publish_failed':
        'Publish failed. Please try again later.',
    'admin_ad_promotion_paused_ok': 'Promotion post paused.',
    'admin_ad_promotion_republish_ok': 'Promotion post republished.',
    'admin_ad_promotion_title_required': 'Please enter a title first.',
    'admin_ad_promotion_content_required':
        'Please provide content, a link, or an image.',
    'admin_ad_promotion_invalid_image':
        'Unsupported image format or processing failed. Please use JPG / PNG.',
    'ad_coop_notify_approved': 'Your ad post content has been approved.',
    'ad_coop_notify_revision': 'Please revise your ad post:',
    'ad_coop_notify_dismiss': 'Dismiss',
    'ad_coop_billing_notify_title': 'Ad promotion notice',
    'admin_sec_j': 'Ad expiry reminders',
    'admin_sec_k': 'Suspected violation posts',
    'admin_sec_k_empty': 'No posts pending review',
    'admin_sec_k_approved': 'Approved and published to invitations feed',
    'admin_sec_k_rejected': 'Rejected and removed from queue',
    'admin_sec_k_tab_pending': 'Pending review',
    'admin_sec_k_tab_reports': 'Member reports',
    'admin_sec_k_reports_empty': 'No pending reports',
    'admin_report_post_label': 'Post ID',
    'admin_report_author_label': 'Author',
    'admin_report_reason_label': 'Report detail',
    'admin_report_ignore': 'Dismiss',
    'admin_report_delete_post': 'Delete post',
    'admin_report_warn': 'Warn',
    'admin_report_blacklist': 'Blacklist',
    'admin_report_ignored': 'Marked as dismissed',
    'admin_report_deleted': 'Public post deleted',
    'admin_report_warned': 'Member warned (please edit post)',
    'admin_report_blacklisted': 'User blacklisted (account synced)',
    'moderation_contact_blocked':
        'Phone numbers, emails, URLs, or social contacts are not allowed. Edit your text.',
    'feed_report_button': 'Report',
    'feed_report_title': 'Report violation',
    'feed_report_hint':
        'Briefly describe the issue (e.g. harassment, inappropriate image, leaked contact info).',
    'feed_report_field_hint': 'Describe the violation…',
    'feed_report_submit': 'Submit',
    'feed_report_cancel': 'Cancel',
    'feed_report_ok': 'Report submitted. Staff will review.',
    'feed_report_need_login': 'Sign in to report.',
    'feed_report_empty': 'Please enter a description.',
    'feed_report_fail': 'Submit failed',
    'moderation_blocked':
        'Your text contains disallowed language and cannot be published.',
    'moderation_queued':
        'Your post was sent for admin review. It will appear in Invitations after approval.',
    'moderation_need_login_review': 'Sign in to submit posts for admin review.',
    'duplicate_same_day':
        'You already posted the same content within the last 24 hours. Edit the text or try again later.',
    'my_posts_header':
        'Published posts (avoid posting the same content twice within 24 hours):',
    'my_posts_empty': 'No published posts yet',
    'post_edit': 'Edit',
    'post_delete': 'Delete',
    'post_edit_hint': 'Post text',
    'confirm_delete_post_title': 'Delete this post?',
    'post_deleted': 'Post deleted',
    'post_delete_failed': 'Could not delete. Please try again.',
    'post_updated': 'Post updated',
    'moderation_suspected_edit':
        'Your edit needs admin review before it appears.',
    'load_more_feed': 'Load more',
    'feed_post_image_title': 'Post image',
    'feed_post_image_hint':
        'Separate from the profile photo above; shown on the Invitations feed (optional).',
    'feed_post_image_tap': 'Tap to upload',
    'image_moderation_blocked':
        'Image failed safety checks (inappropriate content or invalid file) and cannot be posted.',
    'admin_sec_a_add': 'Add directory entry',
    'admin_sec_a_new_expand': 'Add admin account',
    'admin_sec_a_account_name': 'Admin account name',
    'admin_sec_a_recovery_email': 'Recovery email (password reset)',
    'admin_sec_a_password_hint':
        'If you set a password, an Authentication user is created with the recovery email (must be unique). Leave blank to only add the roster row; create the user in Console later.',
    'admin_sec_a_set_password': 'Set password (optional)',
    'admin_sec_a_submit': 'Submit',
    'admin_sec_a_list_title': 'Existing admin accounts',
    'admin_sec_a_col_name': 'Account name',
    'admin_sec_a_col_reset': 'Reset password',
    'admin_sec_a_col_recovery': 'Recovery email',
    'admin_sec_a_col_delete': 'Delete',
    'admin_sec_a_col_manual_reset': 'Reset password',
    'admin_sec_a_manual_reset_title': 'Reset roster login password',
    'admin_sec_a_manual_reset_hint':
        'The new password will match Admin Login (account name is the name in the first column).',
    'admin_sec_a_new_password': 'New password',
    'admin_sec_a_confirm_password': 'Confirm password',
    'admin_sec_a_password_mismatch': 'Passwords do not match',
    'admin_sec_a_manual_reset_submit': 'OK',
    'admin_sec_a_manual_reset_ok': 'Updated. Sign in with the new password.',
    'admin_sec_a_change_password': 'Send reset email',
    'admin_sec_a_reset_sent': 'Password reset email sent',
    'admin_sec_a_reset_fail': 'Send failed',
    'admin_sec_a_recovery_required': 'Recovery email is required',
    'admin_sec_a_required_fields': 'Enter account name and recovery email',
    'admin_sec_a_added': 'Directory entry added',
    'admin_sec_a_added_no_password':
        'Added to the roster without a login password yet. Enter a password and submit again, or ask another admin to use Reset password.',
    'admin_sec_a_added_shared_email':
        'This email is already a member or Firebase user. Added to the admin roster only (same person can be both). No duplicate Auth user was created; password reset goes to that existing account.',
    'admin_sec_a_add_fail': 'Add failed',
    'admin_sec_a_edit_recovery': 'Edit recovery email',
    'admin_forgot_enter_account': 'Account',
    'admin_forgot_enter_email': 'Recovery email',
    'admin_forgot_submit': 'Send password reset email',
    'admin_forgot_mismatch':
        'Account and recovery email do not match the directory',
    'admin_forgot_sent':
        'If your details are correct, a reset email has been sent.',
    'admin_forgot_firebase':
        'Firebase is not ready; cannot verify roster or send email.',
    'admin_forgot_roster_body':
        'Admin sign-in passwords are stored in the Admin Accounts roster. If you forgot yours, ask another admin who can sign in to use “Reset password” in the roster for your account.',
    'admin_forgot_fail': 'Request failed',
    'admin_sec_display_name': 'Display name',
    'admin_sec_note': 'Notes',
    'admin_sec_empty': 'No data yet',
    'admin_sec_deleted': 'Deleted',
    'admin_sec_b_tab_members': 'Members & stats',
    'admin_sec_b_tab_blacklist': 'Blacklist',
    'admin_sec_b_total': 'Total registered members',
    'admin_sec_b2_add': 'Add to blacklist',
    'admin_sec_c_add_order': 'Add order',
    'admin_sec_c_monthly': 'Orders this month',
    'admin_sec_c_monthly_paid_line': 'Paid this month: {amount}',
    'admin_sec_c_renewal_total': 'Auto-renewals: {n}',
    'admin_sec_c_expiry_hint': 'Expiring in next 30 days',
    'admin_sec_c_expires': 'Expires',
    'admin_sec_c_plan': 'Plan code',
    'admin_sec_c_member': 'Member',
    'admin_sec_c_order_status': 'Order status',
    'admin_sec_c_deal_done': 'Completed',
    'admin_sec_c_deal_pending': 'Not completed',
    'admin_pay_other': 'Other',
    'admin_sec_c_receipt_missing': 'No receipt uploaded yet',
    'admin_sec_c_mark_paid_needs_receipt':
        'This payment type requires a receipt image before marking as paid.',
    'admin_sec_c_pay_state': 'Payment',
    'admin_sec_c_paid': 'Paid',
    'admin_sec_c_unpaid': 'Unpaid',
    'admin_sec_c_btn_mark_paid': 'Mark paid',
    'admin_sec_c_receipt': 'Receipt',
    'admin_sec_c_pay_method': 'Payment method',
    'admin_sec_c_order_time': 'Order time',
    'admin_pay_manual_fps_wechat_bank':
        'Other (FPS / WeChat Pay / bank transfer)',
    'admin_pay_other_demo_web': 'Other (demo / IAP N/A on web)',
    'admin_pay_other_demo': 'Other (demo)',
    'admin_pay_stripe': 'Legacy disabled payment',
    'admin_pay_iap_ios': 'App Store (IAP)',
    'admin_pay_iap_android': 'Google Play (IAP)',
    'admin_sec_d_add': 'Add to pool',
    'admin_sec_e_criteria': 'Matching criteria',
    'admin_sec_e_push': 'Event push (notification queue)',
    'admin_sec_e_push_btn': 'Queue push',
    'admin_sec_e_push_queued': 'Queued to notifications',
    'admin_sec_e_activity_orders': 'Activity order count',
    'admin_sec_e_monthly_count': 'This month: {n} orders',
    'admin_sec_e_monthly_paid_label': 'Paid',
    'admin_sec_e_monthly_paid_total': 'Month total: {amount}',
    'admin_sec_e_activity_empty':
        'No activity sign-up orders yet (appear after members register on the Activities tab).',
    'admin_sec_e_purged_unpaid':
        'Removed {n} unpaid activity order(s) older than one month.',
    'admin_purge_unpaid_orders_snackbar':
        'Removed {n} unpaid order(s) older than one month (subscription / ads / activities).',
    'admin_manual_sweep_title': 'Run Manual Billing Sweep',
    'admin_manual_sweep_body':
        'Run the manual monthly billing sweep immediately instead of waiting for the daily scheduler. This will send due reminders, suspend overdue unpaid members, and refresh related order/member status right away.',
    'admin_manual_sweep_btn': 'Run sweep now',
    'admin_manual_sweep_running': 'Running…',
    'admin_manual_sweep_done':
        'Manual monthly billing sweep completed. Updated {n} record(s).',
    'admin_ad_coop_sweep_done':
        'Ad promotion monthly billing sweep completed. Updated {n} record(s).',
    'admin_activity_summary': 'Event description',
    'admin_sec_f_add': 'New event',
    'admin_sec_f_upload_image': 'Upload image',
    'admin_sec_f_images': 'Image URLs (comma-separated)',
    'admin_sec_f_payment': 'Payment notes',
    'admin_sec_f_gmail': 'Gmail flag (send via Cloud Functions)',
    'admin_sec_f_price': 'Price',
    'admin_sec_f_activity_detail': 'Event details (signup page)',
    'admin_sec_f_event_poster_upload':
        'Upload event poster (top-right on “Learn more” sheet)',
    'admin_sec_f_view_activity_detail': 'View event details',
    'admin_sec_f_remove_event_poster': 'Remove poster',
    'admin_sec_f_tap_area_to_upload': 'Tap inside the frame to upload',
    'admin_sec_f_poster_rules':
        'JPG or PNG only; max 5MB per file (larger files are compressed automatically).',
    'admin_sec_f_poster_invalid_format': 'Please choose a JPG or PNG image.',
    'admin_sec_f_list_poster_placeholder': 'Image',
    'admin_sec_f_activity_detail_hint':
        'Shown below the title, e.g. schedule, venue, notes',
    'admin_sec_f_body_hint':
        'Body text for listing/sync; if Price is empty, the first line may be used as price (legacy).',
    'admin_sec_f_activity_dates_title': 'Event dates',
    'admin_sec_f_activity_dates_hint':
        'Add multiple dates; members pick one via a horizontal scroller on signup. Leave empty to hide.',
    'admin_sec_f_activity_dates_add': 'Add date field',
    'admin_sec_f_activity_date_placeholder': 'e.g. Sat 14 Jun 2025',
    'admin_sec_f_registration_cap':
        'Headcount per signup (1–10); no total event capacity limit',
    'pay_choice_iap': 'App Store / Google Play',
    'pay_choice_stripe': 'Legacy web payment (disabled)',
    'pay_choice_manual': 'FPS / WeChat / bank transfer',
    'payment_manual_orange_hint_above':
        'Tap the orange button below to pay',
    'subscription_iap_subtitle':
        'Pay with App Store or Google Play on your device',
    'subscription_stripe_subtitle': 'This payment method has been disabled',
    'subscription_manual_subtitle':
        'Tap the orange button above to pay',
    'activity_details_label': 'Event details',
    'activity_reg_event_date': 'Event date',
    'activity_reg_pick_event_date': 'Select event date',
    'activity_reg_swipe_right_select_gt': 'Swipe right to select »',
    'activity_reg_swipe_right_select': 'Swipe right to select',
    'activity_tap_image_enlarge': 'Tap to enlarge',
    'activity_scroll_pay_banner':
        'Scroll down to pay and complete registration',
    'activity_scroll_down_hint': 'Scroll down',
    'activity_reg_headcount': 'Participants',
    'activity_choose_payment': 'Payment method',
    'activity_payment_tap_hint':
        'Tap the orange button above to pay',
    'activity_login_required':
        'Sign in with a member account (not guest) to register and pay.',
    'activity_order_failed': 'Could not create order. Check login and network.',
    'activity_stripe_url_missing':
        'This legacy web payment method has been disabled.',
    'activity_order_manual_snackbar':
        'Activity signup submitted. Please send your receipt on WhatsApp.',
    'activity_whatsapp_prefill': 'I want to join the event: ',
    'activity_whatsapp_prefill_tail': ' people, total ',
    'activity_iap_demo_snackbar': '(Demo) Activity signup recorded.',
    'activity_iap_use_app': 'For in-app purchase, use the iOS or Android app.',
    'admin_sec_f_saving': 'Saving…',
    'admin_sec_f_sync_failed':
        'Saved to admin, but failed to sync the public activity list: {error}. Check network or refresh the Activities page.',
    'admin_sec_f_empty_hint':
        'Tap “New event”, then fill title, event details (signup page), registration cap, price, and payment method; Save syncs to the public Activities page.',
    'admin_sec_f_title_required': 'Enter an event title',
    'admin_sec_f_delete_confirm': 'Delete this event? This cannot be undone.',
    'admin_sec_g_emails': 'Report emails (comma-separated)',
    'admin_sec_g_cadence': 'Cadence',
    'admin_sec_g_monthly': 'Monthly',
    'admin_sec_g_weekly': 'Weekly',
    'admin_sec_h_new': 'New test request',
    'admin_sec_company': 'Company / name',
    'admin_sec_contact': 'Contact',
    'admin_sec_approve': 'Approve',
    'admin_sec_reject': 'Reject',
    'admin_sec_reject_reason': 'Rejection reason (required)',
    'admin_sec_h_approved': 'Approved',
    'admin_sec_j_empty': 'No approved ads expiring within 14 days',
    'admin_sec_j_expires': 'Expires',
    'admin_field_uid': 'Member UID',
    'admin_field_reason': 'Reason',
    'admin_sec_saved': 'Saved',
    'admin_save_failed': 'Save failed',
    'admin_src_a':
        'Firestore admin_accounts: admin roster (separate from in-app admin password). Fields: displayName, note, active, createdAt.',
    'admin_src_b':
        'users: synced with signup/profile (memberNo, email, displayName, phone, gender, age, subscriptionActive, tags, sentence, avatar, updatedAt). user_blacklist blocks by UID.',
    'admin_src_c':
    'subscription_orders: manual orders; payments & subscriptions: app/IAP and legacy payment records.',
    'admin_src_d':
        'upgrade_matching_pool: upgraded matching pool; sync from users.subscriptionActive=true. See also matches, users for discovery.',
    'admin_src_e':
        'match_admin_settings: criteria; notifications type=admin_event: push queue (FCM via Cloud Functions).',
    'admin_src_f':
        'event_cms: admin event copy; app activity list uses activities (ActivityFirestoreService).',
    'admin_src_g':
        'event_proposals: member-submitted event plans; set status to approved or rejected.',
    'admin_src_h':
        'ad_partner_requests status=pending; rejectReason required when rejected.',
    'admin_src_i': 'Same collection status=approved: approved cases.',
    'admin_src_j':
        'Same collection approved with expiresAt within window: expiry reminders (Scheduler/Functions).',
    'admin_sec_c_app_records':
        'App payments / subscriptions (read-only preview)',
    'admin_sec_d_sync': 'Sync subscribed members into pool',
    'admin_sec_d_sync_ok': 'Synced',
    'admin_sec_member_no': 'Member no.',
    'admin_sec_b_reg_date': 'Registered',
    'admin_sec_b_add_blacklist': 'Blacklist',
    'admin_sec_b2_checkbox_reason': 'Checked in admin list',
    'admin_sec_subscribed': 'Subscribed',
    'admin_sec_b_cleanup_scan': 'Scan & delete incomplete placeholders',
    'admin_sec_b_cleanup_title': 'Delete placeholder profiles',
    'admin_sec_b_cleanup_body':
        'Deletes users documents where job is 「未填寫」 and sentence is still the system default. Up to 500 job=未填寫 per run. Excludes your current Firebase UID.',
    'admin_sec_b_cleanup_found': 'Matching',
    'admin_sec_b_cleanup_confirm': 'Delete',
    'admin_sec_b_cleanup_done': 'Deleted',
    'admin_sec_b_cleanup_none': 'No matching placeholder users',
    'admin_sec_b_cleanup_unit': '',
    'event_proposal_record': 'Event Proposal Records',
    'event_name': 'Event name',
    'event_promo_image': 'Event promo image',
    'event_promo_upload_whatsapp_hint':
        'Upload the promo image — tap WhatsApp on the left～',
    'event_content': 'Event content',
    'event_venue': 'Venue',
    'event_date': 'Date',
    'event_time': 'Time',
    'event_cost': 'Event cost',
    'event_proposal_note':
        'Once your proposed activity is adopted, you can join the event once for free',
    'event_content_placeholder': 'Venue, date, time',
    'adopted': 'Adopted',
    'not_adopted': 'Not adopted',
    'event_proposal_status_passed': 'Approved',
    'event_proposal_status_rejected': 'Not selected',
    'event_proposal_edit_mode': 'Edit proposal',
    'event_proposal_delete_confirm':
        'Delete this proposal record? This cannot be undone.',
    'event_proposal_duplicate':
        'This proposal matches an existing record. Change the text and try again.',
    'event_proposal_submit_failed':
        'Could not submit. Check you are signed in and try again.',
    'event_proposal_login_required':
        'Could not submit. Check your network; if it persists, enable Anonymous sign-in in Firebase Console.',
    'event_proposal_timeout':
        'Timed out (large image or slow network). Try a smaller photo or retry later.',
    'event_proposal_record_modify': 'Edit',
    'event_proposal_image_failed':
        'Image upload failed (storage rules may block uploads). Retry or contact support.',
    'storage_upload_anonymous_no_image':
        'Anonymous sign-in cannot upload images to cloud storage. Sign in with Email, Google, or Apple and try again.',
    'no_event_proposals': 'No event proposal records yet',
    'chat_quota_free_hint':
        'Each day you can message up to 2 different members for free (unlimited messages with each). Same person the same day counts once. After an admin confirms payment, an active subscription lets you message unlimited members.',
    'chat_quota_paywall':
        'Free chat is limited to two members per day. After you successfully subscribe to a plan, you can chat with other members without limit.',
    'chat_quota_dialog_title': 'Free chat limit reached',
    'chat_quota_go_subscribe': 'Subscribe',
    'messaging_requires_invite_accept':
        'Send a chat invite first. Messaging opens after they accept it in Invitations.',
    'heart_counter_invite_followup':
        'You are now connected. Send a chat invite; messaging opens after they accept.',
    'match_mutual_invite_body':
        'You both liked each other! Send a chat invite; messaging opens after they accept.',
    'send_chat_invitation': 'Send invite',
    'chat_invite_interest_body':
        'Someone is interested in your profile. Chat with them?',
    'chat_invite_btn_want': 'Accept',
    'chat_invite_btn_decline': 'Reject',
    'chat_invite_popup_title': 'Chat invite',
    'chat_invite_popup_agree': 'Accept',
    'chat_invite_popup_reject': 'Reject',
    'chat_invite_accept_failed_missing':
        'This invite was not found. Pull to refresh and try again.',
    'chat_invite_accept_failed_already':
        'This invite was already handled (maybe on another device). Pull to refresh.',
    'chat_invite_accept_failed_unknown':
        'Could not accept the invite. Please try again shortly.',
  };
}
